### ISSUE TITLE
Allow the full wm_class value to represent an application

### ISSUE THREAD

**Issue by oblitzitate** [k0kubun/xremap#107]
For instance, King of Fighters '98 UM's full wm_class value is `kingoffighters98um.exe.Wine`. As you can see, the suffix `Wine` alone is too vague and I imagine there might be other apps that share the same suffix.

**Comment by k0kubun** [comment]
makes sense. I plan to replace the X11 client in near future, so let me support it after that change.

**Comment by k0kubun** [comment]
Update: As I'm currently focusing on a big change for another OSS, I'm planning to work on this issue on Aug 13th. If I receive a pull request before that, I can take a look at that too.

**Comment by k0kubun** [comment]
Added the feature in v0.5.3. If your `application` matcher contains `.`, it's now checked against a full WM_CLASS. Note that I only changed the behavior for X11 because you mentioned WM_CLASS.
