### ISSUE TITLE
Provide a way to remap the case "remapped for class: false"

### ISSUE THREAD

**Issue by k0kubun** [k0kubun/xremap#15]
In some situations (like https://github.com/k0kubun/xremap/issues/13), xremap says "remapped for class: false". It may be difficult to remap keys in windows except it.

So we should do following things.

- Research what kind of window has no class and write it as limitation.
- Provide another way to distinguish windows. At least we can know pid and cmdline of it.
  - In that case, xremap should log these information.

**Comment by acro5piano** [comment]
In my environment, the following applications have no class.

- Emacs
- Terminator
- eog
- Firefox developer edition
- pcmanfm

Also the following applications have a class.

- vlc
- chromium
- urxvt

Thanks
