### ISSUE TITLE
Cannot distinguish application names for Java applications

### ISSUE THREAD

**Issue by daigot** [k0kubun/xremap#151]
Hello,

When I'm using IntelliJ IDEA, xremap outputs ```application: Focus-Proxy-Window.FocusProxy``` instead of ```jetbrains-idea```.
So xremap cannot distinguish each Java applications.
I've seen a similar issue of xkeysnail before. https://github.com/mooz/xkeysnail/issues/24

Thanks.

## Environment
- Ubuntu 22.04 (Xorg session)
- xremap-linux-x86_64-x11 0.7.4

**Comment by k0kubun** [comment]
Uh, thanks for reporting it. I think I introduced the bug at either v0.4.6 or v0.5.3. v0.4.5 as you expect, right?

**Comment by daigot** [comment]
Thank you for your quick response.
v0.4.5 works as expected for this issue.

**Comment by k0kubun** [comment]
Addressed this in v0.7.5. Could you test it when you have a chance?

**Comment by daigot** [comment]
v0.7.5 works as I expected so far.
Thank you for the quick fix. :pray:
