### ISSUE TITLE
On Fedora 36, Gnome Shell 42 Wayland, busctl readme instruction return nothing

### ISSUE THREAD

**Issue by stephane-klein** [k0kubun/xremap#153]
On Fedora 36, with Wayland Gnome 42, this command:

```
$ busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'global.get_window_actors().map(a => a.get_meta_window().get_wm_class());'
```

return this:

```
bs false ""
```

Is this normal? Have I made a mistake?

Best regards,
Stéphane

**Comment by k0kubun** [comment]
Gnome 42 no longer supports that. Have you installed https://github.com/xremap/xremap-gnome successfully?

**Comment by stephane-klein** [comment]
> Have you installed https://github.com/xremap/xremap-gnome successfully?

@k0kubun yes 👍

**Comment by k0kubun** [comment]
I finally realized what you're talking about. Please try the following command instead:

```
busctl --user call org.gnome.Shell /com/k0kubun/Xremap com.k0kubun.Xremap WMClass
```

**Comment by stephane-klein** [comment]
> busctl --user call org.gnome.Shell /com/k0kubun/Xremap com.k0kubun.Xremap WMClass

@k0kubun yes, thank, it is working :+1:
