### ISSUE TITLE
Per-application remapping and GNOME 42 - The Return of the Bug

### ISSUE THREAD

**Issue by dottorblaster** [k0kubun/xremap#166]
Hey, first of all, thanks for this majestic piece of software.

Running per-app remappings, I get this again:

```
GnomeClient#connect() failed: I/O error: No such file or directory (os error 2)
GnomeClient#connect() failed: I/O error: No such file or directory (os error 2)
application-client: GNOME (supported: false)
```

I:
- am running `xremap` with sudo;
- am running GNOME 42.4;
- properly edited my DBus session configuration:

```xml
  <policy context="default">
    <allow user="root"/>
    <!-- Allow everything to be sent -->
    <allow send_destination="*" eavesdrop="true"/>
    <!-- Allow everything to be received -->
    <allow eavesdrop="true"/>
    <!-- Allow anyone to own anything -->
    <allow own="*"/>
  </policy>
```

But still looks like the GNOME client doesn't like something in the middle and can't connect to dbus

```sh
blaster@localhost [12:05:28] [~] 
-> % echo $DBUS_SESSION_BUS_ADDRESS                                                                              
unix:path=/run/user/1000/bus
```

The socket file is actually there. I'm really running out of things coming to my mind, my last resort is asking here :smile:

**Comment by dottorblaster** [comment]
Side note: calling busctl and calling the extension method actually works.

```sh
blaster@localhost [12:08:38] [~] 
-> % busctl --user call org.gnome.Shell /com/k0kubun/Xremap com.k0kubun.Xremap WMClass

s "tilix"
```

**Comment by k0kubun** [comment]
> am running xremap with sudo;

Can you try it without sudo? Instructions are at "If you want to run xremap without sudo, click here" in https://github.com/k0kubun/xremap/blob/master/README.md.

**Comment by dottorblaster** [comment]
I tried without sudo, but I keep getting `Failed to prepare an output device: Permission denied (oserror 13)` :/

Really weird, I tried multiple times adding my user to `input` group and following instructions, but I keep getting this and I really don't know how to address it. The problem is showing up on OpenSUSE Tumbleweed, I don't know if this helps. Maybe I should try with another distro :-D

**Comment by k0kubun** [comment]
While the sudo example is an easy way to get started with the remap feature, using sudo rather makes WM integration like per-application remapping hard. If you need per-application remapping, it's sensible to stop using sudo.

The error message indicates that you failed to create a virtual device with uinput. The information on README is based on my experience on Ubuntu and contributors' one on other platforms. If something is different in OpenSUSE, it'd be nice to have your contribution to README about it. Fortunately, configuring udev or using uinput from a non-root user isn't really specific to xremap, so I think you can find OpenSUSE-specific information even if past xremap issues don't have one.

**Comment by dottorblaster** [comment]
Ok, we can close this then and I'll keep trying, when I find out how to do that I'll make a PR with the proper updates on the README.

**Comment by dottorblaster** [comment]
Just trying to debug this on OpenSUSE,

```
drwxr-xr-x   4 root    root           500 16 set 17.37 input
crw-rw-rw-+  1 root    input    10,   223 16 set 17.43 uinput
```

```sh
-> % /home/blaster/.cargo/bin/xremap config.yml
Error: Failed to prepare an output device: Permission denied (os error 13)
```

```sh
-> % getent group input                                                                
input:x:492:brltty,blaster
```

Do you have any pointer? I'm really running out of clues ç_ç

**Comment by k0kubun** [comment]
I searched "opensuse uinput permission" and ran into https://github.com/tbocek/dvorak/issues/1. Can you try creating uinput group, adding yourself to the uinput group, adding a udev rule for it https://github.com/tuomasjjrasanen/python-uinput/blob/master/udev-rules/40-uinput.rules, and rebooting your machine?

**Comment by dottorblaster** [comment]
Ok, I finally found a spare evening to debug this and I discovered that on OpenSUSE the solution is to use a specific tag, thanks to a nested comment [on StackOverflow](https://stackoverflow.com/questions/11939255/writing-to-dev-uinput-on-ubuntu-12-04)

```sh
-> % cat /etc/udev/rules.d/99-input.rules 
SUBSYSTEM=="misc", KERNEL=="uinput", GROUP="uinput", MODE="0666", TAG+="uaccess"
```

Would you be interested in a PR that updates he README in such a way? And: this looks like something really cross-distro, that users would be interested about. If I update the README, should I phrase this like something SUSE specific or something more generic?

**Comment by k0kubun** [comment]
Congrats :tada: Thank you for your research.

Yes, that'd be appreciated. Let's try saying that it's a generic method first, and then update that to SUSE specific when it's found otherwise. It'd be nice to take what Berwyn said into account too.

**Comment by dottorblaster** [comment]
After some further research, this is the content of my udev rule:

```sh
-> % cat /etc/udev/rules.d/99-input.rules
KERNEL=="uinput", GROUP="input", TAG+="uaccess"
```

I think I can make a PR enriching the current rule in the README with the TAG statement, what do you think?

**Comment by k0kubun** [comment]
sounds good to me.

**Comment by berwynhoyt** [comment]
Helpful. I have included this in my own [xremap installer](https://github.com/berwynhoyt/wordstar-keys/tree/main/xremap).

**Comment by dottorblaster** [comment]
Super glad of the result of this research! Thank you both :heart:
