### ISSUE TITLE
Support for scrollwheel events

### ISSUE THREAD

**Issue by timbertson** [k0kubun/xremap#180]
I did a little hacking locally to try and add scrollwheel events. Specifically I'd like to switch tabs on alt+scrollwheel, so I only want to remap scroll events, not produce them.

My basic idea is that there are already SCROLLUP and SCROLLDOWN keys. For the purpose of config, it seems convenient to (re)use these for mapping mouse wheel events.

The actual events are different, they come through as RelAxis(REL_WHEEL) events. There's a couple of options for the implementation, so I thought I'd see what you prefer before submitting any PRs:

 1. Before processing an event, **rewrite REL_WHEEL events into SCROLLUP/SCROLLDOWN key events**. Whenever we emit a SCROLLUP/SCROLLDOWN, rewrite it back into a REL_WHEEL event
    - This is the smallest amount of code change, most of the code treats them as regular key presses.
    - This would end up rewriting any _actual_ SCROLLUP/SCROLLDOWN keyboard events into scroll events, even if you don't have any related mappings. That seems rude.
2. Introduce a **new struct with `key, value, event` fields**.
    - For key events the key and value would duplicate what's in the event, but for scroll events we could now represent `{ key: SCROLLUP, value: PRESS, event: RelAxis(REL_WHEEL, ...) }`. i.e. process mapping as if it were a SCROLLUP keypress event, but if it doesn't get remapped, emit the original event.
    - This has the lowest chance of breaking things, and the code seems clearer.
    - This type would need to be used in all the places we pass around `(key, value)` today, so it's not a small diff.
    - There's still some ambiguity in how we choose to emit a SCROLLUP which is produced by a remapping. We could probably leave it as a key, and hope it has the intended effect?
3. Introduce **an enum which is either a KeyEvent(key, value) or a ScrollEvent(direction)**
    - This is perhaps the most principled, but would require even more code changes.
    - This only makes sense if we want to treat scrollwheel events differently to SCROLLUP/SCROLLDOWN buttons. For that we'd have to invent new symbols like MOUSE_SCROLL_UP and MOUSE_SCROLL_DOWN, which means we couldn't represent them with a `Key` (which would require a lot of changes).

I'd like to implement option (2), but I'm happy to go with your preference.

**Comment by k0kubun** [comment]
I've never played with the interface myself, so I can't give you a meaningful opinion. Can you go with an option that you think would be the simplest?

**Comment by GitPerseus** [comment]
Hey, i have an option that supports transforming all relative events into other stuff through modmap, 
and can also support either keymap or blocking remapped relative events, would you be interested?

**Comment by k0kubun** [comment]
If you make it a pull request, I can have a look at it as well when I have a chance. I'm back at my home but basically killed by many other chores after a long trip so far.

**Comment by GitPerseus** [comment]
Thanks.
Here is my pull request : https://github.com/k0kubun/xremap/pull/187
(This is the version that supports keymap but not blocking relative events that have been remapped.)

**Comment by k0kubun** [comment]
Now I'm finally back to looking into xremap issues.

Can either of you explain the relationship between https://github.com/k0kubun/xremap/pull/181 and https://github.com/k0kubun/xremap/pull/187? I'm still new to those events. Given that https://github.com/k0kubun/xremap/pull/181 implemented option (2), is https://github.com/k0kubun/xremap/pull/187 option (1) or (3)? Does https://github.com/k0kubun/xremap/pull/187 solve the problem Tim wanted to address?

**Comment by timbertson** [comment]
I've added some comments to both PRs which clarify the relationship from an implementation perspective.

#187 is none of the options I listed here. It's closest to (2), except that instead of having a single struct with (key, code, original), it uses a boolean flag to trigger a different code path based on whether we should use the key+code or the original. It would be possible to rewrite #187 to use the same approach as #181, which might make them easier to compare.

The functional difference between the PRs is that my #181 only supports remapping scroll up/down events, and it does so by treating them as the (existing) SCROLLUP/SCROLLDOWN keycodes. #187 introduces a new set of (fake) keycodes in evdev to represent all of the various scroll event types. That means #187 supports more events, but I'm not sure if the proposed changes will be accepted by evdev. If they're not, we'd need to find some other way of introducing a bunch of fake keys.

**Comment by timbertson** [comment]
To help compare differences, I've distilled the functional differences by rewriting #187 on top of #181. Ignoring the plumbing changes required to pass through the original event, the changes to support scroll events look like this:

#181: https://github.com/timbertson/xremap/compare/scrollwheel-compare-base...timbertson:xremap:scrollwheel-compare-a
#187: https://github.com/timbertson/xremap/compare/scrollwheel-compare-base...timbertson:xremap:scrollwheel-compare-b

This isn't _quite_ accurate, as #187 actually treats such an event as a sequence of PRESS + RELEASE. While the above branches only treat a scroll event as a single PRESS, without a RELASE. I don't believe this matters in practice since the only event we map is PRESS, release is only really necessary for modifier keys. But calling that out in case you think it matters.

**Comment by GitPerseus** [comment]
I agree with most of what Tim said, there's just one part i'm not sure i understand : 
Wouldn't sending only a PRESS without a RELEASE make using modmap somewhat impractical?

As for the need of a custom version of evdev,
my latest commit uses the [custom aliases list](https://github.com/k0kubun/xremap/blob/b71e1f0162a1a2437d3603166b400802db850f91/src/config/key.rs#L52-L107) to add custom scancodes from there.

**Comment by timbertson** [comment]
> Wouldn't sending only a PRESS without a RELEASE make using modmap somewhat impractical?

I don't think so, though @k0kubun will know for sure :)

The standalone PRESS event is only used for remapping purposes. If you remap it to the letter `x`, then xremap will send an `x press` followed by an `x release`. If you _don't_ remap it, then xremap will send the original mouse event. So I don't think there's a case when we actually emit a PRESS without a RELEASE.

**Comment by GitPerseus** [comment]
> The standalone PRESS event is only used for remapping purposes. If you remap it to the letter `x`, then xremap will send an `x press` followed by an `x release`. If you _don't_ remap it, then xremap will send the original mouse event. So I don't think there's a case when we actually emit a PRESS without a RELEASE.

I did try running your code with modmap using the following config file : 
```
modmap:
  - name: Global
    remap:
      KEY_SCROLLUP: KEY_S
      KEY_SCROLLDOWN: KEY_S

```
Scrolling did not send a RELEASE event,
which meant "S" stayed pressed,
(at least until the real "S" key was pressed)
which is easily visible while trying to write somewhere, such as the terminal.
