### ISSUE TITLE
How to run at startup?

### ISSUE THREAD

**Issue by navakelvin** [k0kubun/xremap#188]
Forgive my ignorance on this part. How to make xremap config.yml run silently at system startup?

Doing the no-sudo configuration first. I have tried without success:
- Put xremap in /usr/local/bin/ and create ~/.config/autostart/xremap.desktop
```shell
[Desktop Entry]
Name=Xremap
Type=Application
Exec=xremap ~/.config/xremap/config.yml
Terminal=false
```
- Create a service in /etc/systemd/user/xremap.service
```
[Service]
ExecStart=/usr/local/bin/xremap ~/.config/xremap/config.yml
```

**Comment by k0kubun** [comment]
> I have tried without success:

You need to be more specific as to how it failed if you need assistance.

> Put xremap in /usr/local/bin/ and create ~/.config/autostart/xremap.desktop
> Create a service in /etc/systemd/user/xremap.service

Can you try the following configs instead first? Yours is slightly different from what I use.

```sh
# ~/.config/systemd/user/xremap.service
[Unit]
Description=xremap

[Service]
Restart=always
ExecStart=xremap ~/config/xremap.yml --watch`
```

```sh
# ~/.config/autostart/xremap.desktop
[Desktop Entry]
Name=Xremap
Type=Application
Exec=systemctl --user start xremap
Terminal=false
```

Also, if it doesn't work, please include the full output for each of the following commands:

* `xremap ~/config/xremap.yml --watch`
* `systemctl --user start xremap`
  * its logs `journalctl --user -u xremap`

---

I'll close this because this doesn't seem like an issue of xremap. But I'll continue to help you while the ticket is closed.

**Comment by navakelvin** [comment]
> Also, if it doesn't work, please include the full output for each of the following commands:
> 
> * `xremap ~/config/xremap.yml --watch`
> * `systemctl --user start xremap`
>   
>   * its logs `journalctl --user -u xremap`
> 
> I'll close this because this doesn't seem like an issue of xremap. But I'll continue to help you while the ticket is closed.

---

 `xremap ~/config/xremap.yml --watch` return:
```
Selecting devices from the following list:
------------------------------------------------------------------------------
/dev/input/event0 : Power Button
/dev/input/event1 : Power Button
/dev/input/event10: HDA Intel PCH Line Out
/dev/input/event11: HDA Intel PCH Front Headphone
/dev/input/event12: HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event2 : CASUE USB KB
/dev/input/event3 : CASUE USB KB Consumer Control
/dev/input/event4 : CASUE USB KB System Control
/dev/input/event5 : Video Bus
/dev/input/event6 : SIGMACHIP Usb Mouse
/dev/input/event7 : HDA Intel PCH Front Mic
/dev/input/event8 : HDA Intel PCH Rear Mic
/dev/input/event9 : HDA Intel PCH Line
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
/dev/input/event2 : CASUE USB KB
------------------------------------------------------------------------------
```

AND.

`systemctl --user start xremap`
`journalctl --user -u xremap` return:
```shell
oct 10 14:25:16 linux systemd[994]: Started xremap.
oct 10 14:25:16 linux xremap[2105]: Error: Failed to load config '~/.config/xremap/config.yml': No such file or directory (os error 2)
oct 10 14:25:16 linux systemd[994]: xremap.service: Main process exited, code=exited, status=1/FAILURE
oct 10 14:25:16 linux systemd[994]: xremap.service: Failed with result 'exit-code'.
oct 10 14:25:17 linux systemd[994]: xremap.service: Scheduled restart job, restart counter is at 1.
oct 10 14:25:17 linux systemd[994]: Stopped xremap.
oct 10 14:25:17 linux systemd[994]: Started xremap.
oct 10 14:25:17 linux xremap[2109]: Error: Failed to load config '~/.config/xremap/config.yml': No such file or directory (os error 2)
oct 10 14:25:17 linux systemd[994]: xremap.service: Main process exited, code=exited, status=1/FAILURE
oct 10 14:25:17 linux systemd[994]: xremap.service: Failed with result 'exit-code'.
oct 10 14:25:17 linux systemd[994]: xremap.service: Scheduled restart job, restart counter is at 2.
oct 10 14:25:17 linux systemd[994]: Stopped xremap.
oct 10 14:25:17 linux systemd[994]: Started xremap.
oct 10 14:25:17 linux xremap[2110]: Error: Failed to load config '~/.config/xremap/config.yml': No such file or directory (os error 2)
oct 10 14:25:17 linux systemd[994]: xremap.service: Main process exited, code=exited, status=1/FAILURE
oct 10 14:25:17 linux systemd[994]: xremap.service: Failed with result 'exit-code'.
oct 10 14:25:17 linux systemd[994]: xremap.service: Scheduled restart job, restart counter is at 3.
oct 10 14:25:17 linux systemd[994]: Stopped xremap.
oct 10 14:25:17 linux systemd[994]: Started xremap.
oct 10 14:25:17 linux xremap[2111]: Error: Failed to load config '~/.config/xremap/config.yml': No such file or directory (os error 2)
oct 10 14:25:17 linux systemd[994]: xremap.service: Main process exited, code=exited, status=1/FAILURE
oct 10 14:25:17 linux systemd[994]: xremap.service: Failed with result 'exit-code'.
oct 10 14:25:17 linux systemd[994]: xremap.service: Scheduled restart job, restart counter is at 4.
oct 10 14:25:17 linux systemd[994]: Stopped xremap.
oct 10 14:25:17 linux systemd[994]: Started xremap.
oct 10 14:25:17 linux xremap[2112]: Error: Failed to load config '~/.config/xremap/config.yml': No such file or directory (os error 2)
oct 10 14:25:17 linux systemd[994]: xremap.service: Main process exited, code=exited, status=1/FAILURE
oct 10 14:25:17 linux systemd[994]: xremap.service: Failed with result 'exit-code'.
oct 10 14:25:18 linux systemd[994]: xremap.service: Scheduled restart job, restart counter is at 5.
oct 10 14:25:18 linux systemd[994]: Stopped xremap.
oct 10 14:25:18 linux systemd[994]: xremap.service: Start request repeated too quickly.
oct 10 14:25:18 linux systemd[994]: xremap.service: Failed with result 'exit-code'.
oct 10 14:25:18 linux systemd[994]: Failed to start xremap.
```

**Comment by k0kubun** [comment]
> oct 10 14:25:17 linux xremap[2112]: Error: Failed to load config '~/.config/xremap/config.yml': No such file or directory (os error 2)

Can you replace `~/` with the actual absolute path in the config?

**Comment by navakelvin** [comment]
> > oct 10 14:25:17 linux xremap[2112]: Error: Failed to load config '~/.config/xremap/config.yml': No such file or directory (os error 2)
> 
> Can you replace `~/` with the actual absolute path in the config?

Changing `~/` to `/home/my-user/` made it work. The service starts with the system by placing the entry in autostart.

This ticket with this particular problem you can consider it solved. Thank you for that, sir. 

P.S. I have this other ticket open https://github.com/k0kubun/xremap/issues/189, however I will explain in more detail there so as not to spam this one.

**Comment by eeshugerman** [comment]
I'm curious why y'all are using the `~/.config/autostart/xremap.desktop` file? Here's what I have:
```
[Unit]
Description=xremap

[Service]
Restart=always
ExecStart=xremap --device='AT Translated Set 2 keyboard,Logitech ERGO K860' --watch=device %h/.config/xremap.yml

[Install]
WantedBy=default.target
```
I think the `WantedBy=default.target` bit makes the other file unnecessary. But perhaps there's more to it?

**Comment by k0kubun** [comment]
IIRC, it starts a bit earlier than a certain service that I relied on (which I don't remember). If just using an enabled systemd service works for you, that's perfect. I would do that too if I were you. I might try that again later.
