### ISSUE TITLE
Tab behaves differently when pressing ctrl+shift+tab

### ISSUE THREAD

**Issue by ompugao** [k0kubun/xremap#195]
## Issue
When I try to type ctrl+shift+tab, tab does not work with the following configuration.

```config.yaml
modmap:
  - name: Global
    remap:
      KEY_KATAKANAHIRAGANA: Shift_L
      KEY_CAPSLOCK: Ctrl_L
      KEY_MUHENKAN: Ctrl_L
      KEY_HENKAN: Alt_L
```

According to `$ xev`,
- `KEY_MUHENKAN`+`(original)Shift_L`+`Tab`  -> Tab is recognized as `Shift_L`.
- `KEY_CAPSLOCK`+`(original)Shift_L`+`Tab`  -> Tab is recognized as `ISO_Left_Tab`.
- `KEY_MUHENKAN`+`(original)Shift_R`+`Tab`  -> Tab is recognized as `ISO_Left_Tab`.
- `KEY_CAPSLOCK`+`KEY_KATAKANAHIRAGANA`+`Tab`  -> Tab is recognized as `ISO_Left_Tab`.
- `KEY_MUHENKAN`+`KEY_KATAKANAHIRAGANA`+`Tab`  -> Tab seems not recognized.

The first case and the last case are critical since it behaves as the machine ignores Tab.

## Environment
- OS: ubuntu 18.04, 20.04
- xremap version: 0.7.7 (x11)
- Keyboard:
	- https://www.lenovo.com/jp/ja/p/accessories-and-software/keyboards-and-mice/keyboards/0b47208
	- https://www.lenovo.com/jp/ja/p/accessories-and-software/keyboards-and-mice/keyboards/4y40x49522

Thank you for your great OSS.

**Comment by k0kubun** [comment]
Just to be clear about what's happening, can you start xremap with `RUST_LOG=debug xremap config.yml`, press those five key combinations immediately after that, stop xremap, and share the entire output of the command?

**Comment by ompugao** [comment]
Here you are:
[capslock_katakanahiragana_tab.txt](https://github.com/k0kubun/xremap/files/9837265/capslock_katakanahiragana_tab.txt)
[capslock_shiftl_tab.txt](https://github.com/k0kubun/xremap/files/9837266/capslock_shiftl_tab.txt)
[muhenkan_katakanahiranaga_tab.txt](https://github.com/k0kubun/xremap/files/9837267/muhenkan_katakanahiranaga_tab.txt)
[muhenkan_shiftl_tab.txt](https://github.com/k0kubun/xremap/files/9837268/muhenkan_shiftl_tab.txt)
[muhenkan_shiftr_tab.txt](https://github.com/k0kubun/xremap/files/9837269/muhenkan_shiftr_tab.txt)

> KEY_MUHENKAN+(original)Shift_L+Tab -> Tab is recognized as Shift_L.

this seems wrong. I can say "Tab is not recognized either".

**Comment by ompugao** [comment]
still the same when I swap the remappings for KEY_MUHENKAN and KEY_HIRAGANAKATAKANA as follows.
I may summarise "when ctrl_l is remapped to some key other than CapsLock, tab is not recognized when pressing (remapped)ctrl_l+(original/remapped)shift_l+tab", although it is not fully examined.
```yaml
modmap:
  - name: Global
    remap:
      KEY_CAPSLOCK: Ctrl_L
      KEY_HENKAN: Alt_L
      # KEY_MUHENKAN: Ctrl_L
      # KEY_KATAKANAHIRAGANA: Shift_L
      KEY_MUHENKAN: Shift_L
      KEY_KATAKANAHIRAGANA: Ctrl_L
```

**Comment by ompugao** [comment]
memo:
Muhenkan+

**Comment by ompugao** [comment]
sorry, i unintentionally closed the issue

**Comment by ompugao** [comment]
it seems this is the hardware problem of thinkpad keyboard.
When I check key events with xev, Tab is not recognized when pressing MUHENKAN+SHIFT_L+TAB or MUHENKAN+KATAKANAHIRAGANA+Tab even **without** remapping.
I will close this issue for now.

Sorry to bother you.
