### ISSUE TITLE
device-specific remapping

### ISSUE THREAD

**Issue by tgy** [k0kubun/xremap#201]
hi! thanks for this awesome software! really useful

is there a way to remap only for a specific device?

i have an external typematrix keyboard and there are some keys i want to remap, but only for that keyboard

thx!

**Comment by k0kubun** [comment]
Hi. Yes, there is. I'm not in front of my machine and can't show you how, but there's --device option. Please have a look at "xremap --help", see output of xremap boot, and specify a device name according to the output.

**Comment by tgy** [comment]
thanks for your quick reply! really helpful.

we could add something about that to the README

**Comment by k0kubun** [comment]
Sounds good. Can you make it a pull request?

**Comment by eeshugerman** [comment]
What if I want to remap different things for different devices? Should I run multiple xremap processes with different config files?

**Comment by k0kubun** [comment]
I think we should introduce `device.only` and `device.not` for it, in the same way as `application.only` and `application.not`. Would you be interested in filing a pull request to add that feature?

**Comment by eeshugerman** [comment]
Sweet, yeah, that was going to be my next question! I'll take a stab at it

**Comment by dtcooper** [comment]
Any update on `device.only` and `device.not`? :) Cheers and thanks

**Comment by eeshugerman** [comment]
I haven't made much progress yet. I still intend to make it happen, but can't say when. If someone beats me to it that's fine too :)

**Comment by dtcooper** [comment]
Your branch looks pretty good to me, @eeshugerman! Is it documented? How do I use it?

**Comment by eeshugerman** [comment]
Well I just got it to compile last weekend. Haven't had a chance to test it at all yet so I'd be shocked if it works, but feel free to try it out!

I haven't added documentation yet, but it should work just like `application.only`/`application.not`, which is documented in the README. The strings you provide to identify a device should be the same as those passed to the `--device` flag, which doesn't appear to be documented, but there are some hints [here](https://github.com/k0kubun/xremap/issues/201#issuecomment-1313925478) and [here](https://github.com/k0kubun/xremap/blob/a73ad9cc06e394e595900fe9474893c213ffa3e7/src/device.rs#L232-L245).

**Comment by eeshugerman** [comment]
Update: Just tried it out and it seems to be working. Here's the branch if anyone's interested: https://github.com/eeshugerman/xremap/tree/device-aware-config

Still some work to do on tests and such to get this to a point where it's mergable but I should have PR up before too long.

**Comment by eeshugerman** [comment]
Hi @k0kubun! I still want to get done some day, but I've been stuck on getting the (existing) tests working.

To implement the feature, I've added `InputDevice` to `Event`. So now, in the tests, the events passed to `assert_actions` need some device. What should I use for this? Some kind of mock? As an experiment I tried using my actual keyboard device but then I get `Device or resource busy (os error 16)`.

Please take a look if you have a chance and let me know if you have any suggestions: https://github.com/k0kubun/xremap/compare/master...eeshugerman:xremap:device-aware-config

**Comment by k0kubun** [comment]
Great progress :+1: Thank you for your effort.

> To implement the feature, I've added InputDevice to Event. So now, in the tests, the events passed to assert_actions need some device. What should I use for this?

I'm trying to keep every event free from third-party types as much as possible. We already have an exception, `Key`, but it's a very manageable struct, so I'm using it as is. However, `InputDevice` doesn't seem like something we want to add to the event payload. As you noticed, it's important for testing purposes.

I would extract only the necessary information (e.g. device path and name), make another struct, and embed it into the events. Then you should be able to test it without mocking anything.

**Comment by eeshugerman** [comment]
Thanks for the the tip @k0kubun, that worked out nicely!

At long last, my PR is ready: https://github.com/k0kubun/xremap/pull/380
