### ISSUE TITLE
Executing a command

### ISSUE THREAD

**Issue by medwatt** [k0kubun/xremap#211]
First of all, thanks for `xremap`. I am trying to map `Alt-1` to lunch `kate`, but I am not able to make it work. Am I doing it correctly?

```yaml
keymap:
  - name: Test
    application:
    remap:
      C-b: left
      C-f: right
      M-KEY_1:
         launch: ["bash", "-c", "kate"]
```

**Comment by medwatt** [comment]
This is what I get.

```
/dev/input/event0 : Lid Switch
/dev/input/event1 : Sleep Button
/dev/input/event10: HDA NVidia HDMI/DP,pcm=8
/dev/input/event11: HDA NVidia HDMI/DP,pcm=9
/dev/input/event12: HDA NVidia HDMI/DP,pcm=10
/dev/input/event13: HDA NVidia HDMI/DP,pcm=11
/dev/input/event14: Integrated Camera: Integrated C
/dev/input/event15: HDA Intel PCH Mic
/dev/input/event16: HDA Intel PCH Dock Mic
/dev/input/event17: HDA Intel PCH Dock Headphone
/dev/input/event18: HDA Intel PCH Headphone
/dev/input/event19: Synaptics TM3149-002
/dev/input/event2 : Power Button
/dev/input/event20: PixArt Cherry USB Optical Mouse
/dev/input/event3 : AT Translated Set 2 keyboard
/dev/input/event4 : ThinkPad Extra Buttons
/dev/input/event5 : PC Speaker
/dev/input/event6 : Video Bus
/dev/input/event7 : Video Bus
/dev/input/event8 : HDA NVidia HDMI/DP,pcm=3
/dev/input/event9 : HDA NVidia HDMI/DP,pcm=7
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
/dev/input/event3 : AT Translated Set 2 keyboard
-----------------------------------------------------------
```

There's no output when I trigger the key. Could it be that `kate` gets called but is immediately killed when the process ends?

**Comment by k0kubun** [comment]
As long as xremap is running, a child process should be alive.

Sorry, can you try the same thing with `RUST_LOG=debug xremap`?

**Comment by medwatt** [comment]
This is what I get. No application is opened though.

```
[2022-12-15T06:48:48Z DEBUG xremap::event_handler] => 0: KEY_ENTER
[2022-12-15T06:48:48Z DEBUG xremap::action_dispatcher] 0: KEY_ENTER
[2022-12-15T06:48:49Z DEBUG xremap::event_handler] => 1: KEY_LEFTALT
[2022-12-15T06:48:49Z DEBUG xremap::action_dispatcher] 1: KEY_LEFTALT
[2022-12-15T06:48:49Z DEBUG xremap::event_handler] => 1: KEY_2
[2022-12-15T06:48:49Z DEBUG xremap::action_dispatcher] Running command: ["kate"]
[2022-12-15T06:48:49Z DEBUG xremap::action_dispatcher] Process spawned: ["kate"], pid 96430
[2022-12-15T06:48:49Z DEBUG xremap::event_handler] => 0: KEY_LEFTALT
[2022-12-15T06:48:49Z DEBUG xremap::action_dispatcher] 0: KEY_LEFTALT
[2022-12-15T06:48:49Z DEBUG xremap::event_handler] => 0: KEY_2
[2022-12-15T06:48:49Z DEBUG xremap::action_dispatcher] 0: KEY_2
[2022-12-15T06:48:58Z DEBUG xremap::event_handler] => 1: KEY_LEFTCTRL
[2022-12-15T06:48:58Z DEBUG xremap::action_dispatcher] 1: KEY_LEFTCTRL
[2022-12-15T06:48:58Z DEBUG xremap::event_handler] => 1: KEY_C
[2022-12-15T06:48:58Z DEBUG xremap::action_dispatcher] 1: KEY_C
```

**Comment by k0kubun** [comment]
Do you use `sudo xremap`? If so, can you try running it without sudo on your terminal?

**Comment by medwatt** [comment]
Without `sudo`, this is what I get:

```
Selecting devices from the following list:
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
Error: Failed to prepare input devices: No device was selected!
```

**Comment by k0kubun** [comment]
Could you follow "If you want to run xremap without sudo, click here." in the README https://github.com/k0kubun/xremap/blob/master/README.md?

**Comment by medwatt** [comment]
I tried to make it work without sudo, but I get the error message below.

```
Selecting devices from the following list:
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
Error: Failed to prepare input devices: No device was selected!
```

Running `lsmod` gives the followings:

```
~ ❯ lsmod | grep uinput
uinput                 20480  0
```

I followed the guide for arch linux since I am on Manjaro.

**Comment by k0kubun** [comment]
You only showed the uinput module, but did you add the udev rule and reboot your machine? 

For running xremap without sudo, you need to be able to use `evdev` and `uinput` without sudo. I use Ubuntu, so I can't tell you how to do that on Arch Linux or Manjaro. Have you discovered that information on Arch Linux and tried that?

**Comment by medwatt** [comment]
I managed to get it to work. I was using the instruction on the `README`, which was totally complete. The correct sequence of steps is:

```bash
# create an input group and add the user
sudo usermod -aG input $USER

# create a udev rule
echo 'KERNEL=="uinput", GROUP="input", MODE="0660"' | sudo tee /etc/udev/rules.d/99-input.rules

# reload the udev rules to apply the changes
sudo udevadm control --reload-rules

# logout and log back in
```

Now, I am the command is able to lunch the program. So, I guess this issue is now resolved.

**Comment by medwatt** [comment]
I have one unrelated question if you don't mind.

I am trying to create a keybinding to (1) copy the contents of a file to the clipboard and then (2) paste the content of the clipboard in the focused window.

I created the script shown below and mapped mapped it to a key with `xremap`. The script runs fine, except that the line with `xdotool key Ctrl+v` doesn't seem to work. My question is, is it possible with `xremap` to set a key to trigger at the end?

```bash
xclip -selection clipboard -target image/x-inkscape-svg -i ~/image.svg
xdotool key Ctrl+v
```

**Comment by k0kubun** [comment]
Could you paste an actual config yaml file you're using? I might be able to correct it if I see an actual config.

**Comment by U1s2e3r4n5a6m7e** [comment]
@medwatt  Maybe the problem is `xclip`. I tried with png and it works flawlessly but when I tried with svg it doesn't work.

```yaml
  - name: Copy png svg and Paste
    remap:
      Ctrl-Shift-m:
        launch:
          ["bash", "-c", "xclip -selection clipboard -t image/png -i ~/PNG_Test.png && xdotool key ctrl+v"]
      Ctrl-Shift-n:
        launch:
          ["bash", "-c", "xclip -selection clipboard -t image/x-inkscape-svg -i ~/Test.svg && xdotool key ctrl+v"]
```

[PNG_Test.png file](https://upload.wikimedia.org/wikipedia/commons/6/6a/PNG_Test.png)
[Test.svg file](https://upload.wikimedia.org/wikipedia/commons/b/bd/Test.svg)

**Comment by k0kubun** [comment]
interesting. Does it work if you put `sleep 1` (or something longer) in between those commands in the svg example?

**Comment by U1s2e3r4n5a6m7e** [comment]
It should work without needing `sleep` because It always waits to finish previous command unless used `&` or there is equivalent of `&`  inside the program.

command1; command2_after1; command3_after2
command1 && command2_after1succeeded && command3_after2succeeded

But I tried with 30 seconds on 5KB Test.svg, no luck. It seems `xclip` broken.

**Comment by U1s2e3r4n5a6m7e** [comment]
@medwatt It WORKED!! try with `image/svg+xml` instead of `image/x-inkscape-svg`

source: https://wiki.inkscape.org/wiki/Clipboard#Default_behaviour
