### ISSUE TITLE
Child process killed when xremap restarts

### ISSUE THREAD

**Issue by xiaket** [k0kubun/xremap#213]
Heya,

First off, thanks for your great work my good sir! This works really well for me, it's really good to be able to configure all the key mappings at will.

However, I find a minor inconvenience with the launch directive in the config file, the launched processes are a direct child process of xremap, if we stop xremap for whatever reason(debug/update config for example), the child process dies. Which might not be ideal.

Are you open to use a crate like [fork](https://crates.io/crates/fork) to daemonize the subprocess? Thanks!

**Comment by k0kubun** [comment]
> for whatever reason(debug/update config for example)

Have you considered using `--watch=config`? If it's not enough, then I'm open to demonizing processes created by `launch`.

**Comment by U1s2e3r4n5a6m7e** [comment]
I use like this and It works great:
```
launch:
	["setsid", "firefox-nightly", "--private-window", "--class=Test"]
```

```
launch:
	["setsid", "bash", "-c", "~/.config/rofi/bin/calc_text"]
```
But It would be cool to see implemented natively, something like that: 
`independent: true # Optional and defaults to true`

**Comment by k0kubun** [comment]
Yeah sure. I'll wait for your PR, thanks :) It doesn't need to be an optional flag like `independent: true`. It can be the default and only behavior as the name `launch` implies.
