### ISSUE TITLE
'Handler not found!' occurs  and dose not work in Gnome terminal

### ISSUE THREAD

**Issue by u1tnk** [k0kubun/xremap#23]
## Summary

The following error occurs only for some applications(Gnome terminal, Gnome software).

### Steps

1 lanuch xremap with config
2 launch Gnome terminal and switch
3 Input alt + t

### Logs

```
$  /home/yuichi/local/bin/xremap /home/yuichi/dotfiles/xremap/macos.rb              
Config loaded: #<Xremap::Config:0x83c760 @remaps_by_window={#<struct Xremap::Config::Window class_only=[], class_not=[]>=>[#<struct from_key=#<struct Xremap::Config::Key keysym=116, modifier=8, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=116, modifier=4, action=:input>]>]}, @config_dir="/home/yuichi/dotfiles/xremap">
remapped for class: "gnome-terminal-server"
Handler not found!: [28, 4, {28=>{8=>#<Proc:0x8c4100@/home/yuichi/apps/k0kubun/xremap/mrblib/xremap/key_remap_compiler.rb:26>}}]

```
xremap's configurations

```
remap "Alt-t", to: "C-t"
```

### uname -a

Linux chocobar 4.13.0-041300-generic #201709031731 SMP Sun Sep 3 21:33:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### xremap's latest commit hash

f6918d8ddebfe18640b4f7c77f5dcddb8717bab7

### Gnome Terminal
3.18.3

### Gnome Software
3.20.5

**Comment by k0kubun** [comment]
Reproductive. Thank you for helpful bug report. I'll see its reason later...

By the way, what's "Gnome software"? There are alternatives for Gnome terminal (at least urxvt is working with xremap, in case you need workaround), but it's a concern.

**Comment by u1tnk** [comment]
Sorry, reply was delayed.

"Gnome software" is image below. I am not in trouble because I do not use it much.
![image](https://user-images.githubusercontent.com/279240/31176675-a321abe0-a94e-11e7-98ba-b45de9b77cc9.png)

>  There are alternatives for Gnome terminal (at least urxvt is working with xremap, in case you need workaround), but it's a concern.

Thank you for your concern. I already use  a alternative terminal (termit) without xremap problems.

**Comment by k0kubun** [comment]
I rewrite the whole project, switching from Xlib to evdev + uinput. The reported problem should now be gone with the architecture of the new version. Enjoy!
