### ISSUE TITLE
Add dbus interface

### ISSUE THREAD

**Issue by orowith2os** [k0kubun/xremap#235]
Currently xremap is JSON-only, however it might be preferable for some users to have a GUI. I'd be interested in trying to add a GUI for this project, if you'd be interested in working with me to get it working.

My plan would be to have xremap expose a dbus interface that can be used to control the program, and also allows for the (simple) disconnection of xremap and the GUI, so you can have multiple different frontends (QT, Libadwaita, Iced, etc etc).

Edit: I didn't quite understand how the project worked before making this issue, I tweaked the issue to account for that.

**Comment by orowith2os** [comment]
I think I'm still misunderstanding this, ill give it more thought when I'm free and can fully map how it would work.

**Comment by k0kubun** [comment]
I think you could have a separate GUI application that just modifies a JSON (or YAML). Then, if you run `xremap --watch config`, that would automatically reflect config changes made by the GUI.

**Comment by orowith2os** [comment]
I could, but the idea was to run the GUI without root; I imagine your solution would involve quite a few password prompts and major sandbox escapes (I planned on having the GUI be distributed in flatpak, native packages aren't very fun for them in my experience).

**Comment by k0kubun** [comment]
Not sure what you're talking about. Writing or updating a JSON file doesn't require root or a password prompt unless you put a config under a directory/file owned by root. xremap doesn't restrict the location of a configuration, so you're free to use a directory/file that can be accessed from a non-root user.

**Comment by k0kubun** [comment]
A couple of things you might be missing:

* You don't need sudo to run xremap if you configure it properly; I don't use it.
* It actually doesn't matter whether xremap is run with sudo or not.
  * My intention is that a component that generates a config with GUI should be separate from xremap. The separate component should create/update a file under non-root permission, and xremap should be able to read it whether it's executed with sudo or not.
