### ISSUE TITLE
Logitech ERGO K860 not recognized as a keyboard

### ISSUE THREAD

**Issue by eeshugerman** [k0kubun/xremap#236]
GNOME/Wayland, Arch Linux, kernel 6.1

I sprinkled in some debug logs and it seems the issue is that `keys.contains(Key::BTN_LEFT)` is true for this device. AFAIK this keyboard does not have a left mouse button on it. Please advise.

**Comment by k0kubun** [comment]
What about `BTN_RIGHT`? I guess we could check it instead of `BTN_LEFT` as a workaround if that works better for you. If the keyboard has both, then, well, I'm open to trying just removing `&& !keys.contains(Key::BTN_LEFT)`.

**Comment by eeshugerman** [comment]
Looks like it does have `BTN_RIGHT` as well :slightly_frowning_face:.

Here's the full `keys` value, in case it's of interest:
```
{KEY_ESC, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE, KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_ENTER, KEY_LEFTCTRL, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_GRAVE, KEY_LEFTSHIFT, KEY_BACKSLASH, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_DOT, KEY_SLASH, KEY_RIGHTSHIFT, KEY_KPASTERISK, KEY_LEFTALT, KEY_SPACE, KEY_CAPSLOCK, KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_NUMLOCK, KEY_SCROLLLOCK, KEY_KP7, KEY_KP8, KEY_KP9, KEY_KPMINUS, KEY_KP4, KEY_KP5, KEY_KP6, KEY_KPPLUS, KEY_KP1, KEY_KP2, KEY_KP3, KEY_KP0, KEY_KPDOT, KEY_ZENKAKUHANKAKU, KEY_102ND, KEY_F11, KEY_F12, KEY_RO, KEY_KATAKANA, KEY_HIRAGANA, KEY_HENKAN, KEY_KATAKANAHIRAGANA, KEY_MUHENKAN, KEY_KPJPCOMMA, KEY_KPENTER, KEY_RIGHTCTRL, KEY_KPSLASH, KEY_SYSRQ, KEY_RIGHTALT, KEY_HOME, KEY_UP, KEY_PAGEUP, KEY_LEFT, KEY_RIGHT, KEY_END, KEY_DOWN, KEY_PAGEDOWN, KEY_INSERT, KEY_DELETE, KEY_MUTE, KEY_VOLUMEDOWN, KEY_VOLUMEUP, KEY_POWER, KEY_KPEQUAL, KEY_PAUSE, KEY_SCALE, KEY_KPCOMMA, KEY_HANGEUL, KEY_HANJA, KEY_YEN, KEY_LEFTMETA, KEY_RIGHTMETA, KEY_COMPOSE, KEY_STOP, KEY_AGAIN, KEY_PROPS, KEY_UNDO, KEY_FRONT, KEY_COPY, KEY_OPEN, KEY_PASTE, KEY_FIND, KEY_CUT, KEY_HELP, KEY_MENU, KEY_CALC, KEY_SLEEP, KEY_WAKEUP, KEY_FILE, KEY_WWW, KEY_COFFEE, KEY_MAIL, KEY_BOOKMARKS, KEY_BACK, KEY_FORWARD, KEY_EJECTCD, KEY_NEXTSONG, KEY_PLAYPAUSE, KEY_PREVIOUSSONG, KEY_STOPCD, KEY_RECORD, KEY_REWIND, KEY_PHONE, KEY_CONFIG, KEY_HOMEPAGE, KEY_REFRESH, KEY_EXIT, KEY_EDIT, KEY_SCROLLUP, KEY_SCROLLDOWN, KEY_KPLEFTPAREN, KEY_KPRIGHTPAREN, KEY_NEW, KEY_REDO, KEY_F13, KEY_F14, KEY_F15, KEY_F16, KEY_F17, KEY_F18, KEY_F19, KEY_F20, KEY_F21, KEY_F22, KEY_F23, KEY_F24, KEY_DASHBOARD, KEY_CLOSE, KEY_PLAY, KEY_FASTFORWARD, KEY_BASSBOOST, KEY_PRINT, KEY_CAMERA, KEY_CHAT, KEY_SEARCH, KEY_FINANCE, KEY_CANCEL, KEY_BRIGHTNESSDOWN, KEY_BRIGHTNESSUP, KEY_KBDILLUMTOGGLE, KEY_KBDILLUMDOWN, KEY_KBDILLUMUP, KEY_SEND, KEY_REPLY, KEY_FORWARDMAIL, KEY_SAVE, KEY_DOCUMENTS, KEY_UNKNOWN, KEY_VIDEO_NEXT, KEY_BRIGHTNESS_AUTO, BTN_0, BTN_LEFT, BTN_RIGHT, BTN_MIDDLE, BTN_SIDE, BTN_EXTRA, BTN_FORWARD, BTN_BACK, BTN_TASK, unknown key: 280, unknown key: 281, unknown key: 282, unknown key: 283, unknown key: 284, unknown key: 285, unknown key: 286, unknown key: 287, KEY_SELECT, KEY_GOTO, KEY_INFO, KEY_PROGRAM, KEY_PVR, KEY_SUBTITLE, KEY_ZOOM, KEY_KEYBOARD, KEY_SCREEN, KEY_PC, KEY_TV, KEY_TV2, KEY_VCR, KEY_VCR2, KEY_SAT, KEY_CD, KEY_TAPE, KEY_TUNER, KEY_PLAYER, KEY_DVD, KEY_AUDIO, KEY_VIDEO, KEY_MEMO, KEY_CALENDAR, KEY_RED, KEY_GREEN, KEY_YELLOW, KEY_BLUE, KEY_CHANNELUP, KEY_CHANNELDOWN, KEY_LAST, KEY_NEXT, KEY_RESTART, KEY_SLOW, KEY_SHUFFLE, KEY_PREVIOUS, KEY_VIDEOPHONE, KEY_GAMES, KEY_ZOOMIN, KEY_ZOOMOUT, KEY_ZOOMRESET, KEY_WORDPROCESSOR, KEY_EDITOR, KEY_SPREADSHEET, KEY_GRAPHICSEDITOR, KEY_PRESENTATION, KEY_DATABASE, KEY_NEWS, KEY_VOICEMAIL, KEY_ADDRESSBOOK, KEY_MESSENGER, KEY_DISPLAYTOGGLE, KEY_SPELLCHECK, KEY_LOGOFF, KEY_MEDIA_REPEAT, KEY_IMAGES, KEY_BUTTONCONFIG, KEY_TASKMANAGER, KEY_JOURNAL, KEY_CONTROLPANEL, KEY_APPSELECT, KEY_SCREENSAVER, KEY_VOICECOMMAND, KEY_ASSISTANT, KEY_KBD_LAYOUT_NEXT, unknown key: 585, unknown key: 586, KEY_BRIGHTNESS_MIN, KEY_BRIGHTNESS_MAX, KEY_KBDINPUTASSIST_PREV, KEY_KBDINPUTASSIST_NEXT, KEY_KBDINPUTASSIST_PREVGROUP, KEY_KBDINPUTASSIST_NEXTGROUP, KEY_KBDINPUTASSIST_ACCEPT, KEY_KBDINPUTASSIST_CANCEL}
```

>  well, I'm open to trying just removing `&& !keys.contains(Key::BTN_LEFT)`

Works for me :) Shall I open a PR?

**Comment by eeshugerman** [comment]
By the way, do you know where this data comes from? Is it in the kernel driver? Or hwdb?

**Comment by k0kubun** [comment]
> Works for me :) Shall I open a PR?

Yes, please :)

> By the way, do you know where this data comes from? Is it in the kernel driver? Or hwdb?

I haven't studied that. I just assume a device driver gives what's actually available in hardware to the operating system.

**Comment by eeshugerman** [comment]
Well dang, looks like removing the `BTN_LEFT` check makes my Logitech mouse register as a keyboard :disappointed: . On further inspection I notice the only difference in `keys` for the two is the keyboard has `KEY_WAKEUP`. What's more, `.supported_events()`, `.supported_relative_axes()` are both identical! I tried a few others too and they're pretty much all the same.

I guess one approach would be to check for known `.name()`s, `.unique_name()`s, or `.input_id()`s. I'd be happy to PR that (just let me know which of those three to use), but also I'd completely understand if you want to avoid that sort of thing.

**Comment by k0kubun** [comment]
> I guess one approach would be to check for known .name()s, .unique_name()s, or .input_id()s. I'd be happy to PR that (just let me know which of those three to use), but also I'd completely understand if you want to avoid that sort of thing.

How about adding a field in the config file and using that as the default device selector?

**Comment by eeshugerman** [comment]
Ohhh I just realized I can simply do `--device='AT Translated Set 2 keyboard,Logitech ERGO K860' --watch=device` and my problem is solved! I didn't realize I can pass names to `--device` -- I should have read the help text more closely.

Auto-recognition would be nice, but as long as I don't have to mess with the flags every time I dock or reboot I'm happy.

> How about adding a field in the config file and using that as the default device selector when specified?

Perhaps this would still be good to have though? I'll leave it up to you to leave this open or closed.

Thanks for your help with this!

**Comment by k0kubun** [comment]
If you're happy with `--device`, I'm tempted to close this with that to keep things simple. Thank you!
