### ISSUE TITLE
Error: Evdev & uinput not installed

### ISSUE THREAD

**Issue by rdangdev** [k0kubun/xremap#244]
Hi,

Xremap depends on evdev and uinput to run properly. I am running a new instance of Arch Linux with Hyprland running on Wayland. These two tools don't seem to be installed, nor avaliable in the arch repo. Am i missing something?

Thank you for your time
R.

**Comment by k0kubun** [comment]
I'm not an Arch user, so I'm not sure how to install Arch Linux with evdev and uinput enabled. But I know people who use xremap on Arch Linux, so there should be a way. @chenzaichun might know it since Zai-Chun contributed https://github.com/k0kubun/xremap/pull/216.

**Comment by rdangdev** [comment]
Thanks anyways, I managed to _enable_ uinput by doing a `sudo modprobe uinput` but evdev still is unclear to me

P.S. enabling it through modprobe mounts a device on /dev/uinput, not /dev/misc/uinput. is that going to be an issue?

**Comment by k0kubun** [comment]
evdev handling does expect particular paths, but it's not a problem for uinput. I'm glad you made a progress there.

I also searched how to make evdev available on Arch Linux, but couldn't find useful information yet. But it does seem like Arch Linux users often use evdev. It'd be nice if we can document how to do that in README.md once we find it out.

**Comment by chenzaichun** [comment]
@rdangdev I'm using manjaro with Hyprland right now.

On my system, uinput is mounted as /dev/uinput and everything works well.

**Comment by k0kubun** [comment]
Closing this since it has been answered. Thanks for answering this, Chen.
