### ISSUE TITLE
support river, please

### ISSUE THREAD

**Issue by reuleaux** [k0kubun/xremap#245]
I have been running _xremap_ successfully w/ sway (with the released `xremap-linux-x86_64-sway.zip` v0.8.0 i.e.), however I would like to switch to [river](https://github.com/riverwm/river)

I am running _river_ already successfully (on debian testing), and I would like to take my chromium/firefox _xremap_ _config_ with me.

I tried the package for hypr `xremap-linux-x86_64-hypr.zip` with no success either.

_river_ has its own mapping facility - cf. the docs for _riverctl_ - but it seems less capable:
I don't want to spawn a shell command (that's what riverctl can be used for, typically):
```
riverctl declare-mode cr-ff-browser
riverctl map cr-ff-browser None SomeKeyHere         spawn 'some shell cmd'
```
but I want to send keystrokes to chromium/firefox as remapped with _xremap_
(my config is similar to the [emacs.yml](https://github.com/k0kubun/xremap/blob/master/example/emacs.yml)
one in the examples section)

(But f it is possible to achieve my _emacs_ like _xremap_ mapping with the current _river_
mapping facilities already [? - I doubt it] - then I would like to know, how. - I may ask on the river issue tracker (irc possibly) next. 

Thanks.
  -A

**Comment by k0kubun** [comment]
It's kind of the same request as https://github.com/k0kubun/xremap/issues/141; fortunately, river seems like a wlroots-based compositor. As soon as it gets closed, you'll be able to use that. (Unfortunately, Wayland protocol does not support this kind of capability, which is why I'm targeting the layer of wlroots.)

Note that it's just about `application` filters. You should still be able to use xremap if you don't use `application` filter. But I guess you want to apply some configuration only for Chromium/Firefox?

I don't use Wayland, but I would accept patches to support your platform, whether it's specific to river or something that works for all wlroots-based compositors.

**Comment by reuleaux** [comment]
OK, thanks, and I will have an eye on (the progress of) #141

And yes: I want this emacs like mappings to apply for chromium/firefox
only.

I am not sure, if can supply patches myself (neither am I that much into
_wayland_/_river_/..., nor do I have the time), but maybe I can win some _river_ folks for the idea.

And I don't really care, where the mapping happens: either w/ _xremap_
(once #141 is closed), or in _river_ itself (its mapping facility yet to be improved, I guess) - I just want _emacs_ like keybindings for chromium/firefox in _river_.

Again: thank you so much.
-A

**Comment by k0kubun** [comment]
The wlroots support has been added in v0.8.9. Please try `xremap-linux-x86_64-wlroots.zip`.

**Comment by reuleaux** [comment]
Many thanks, I will give it a try soon.  -AOn 23 Sep 2023, at 07:20, Takashi Kokubun ***@***.***> wrote:﻿
The wlroots support has been added in v0.8.9. Please try xremap-linux-x86_64-wlroots.zip.

**Comment by reuleaux** [comment]
It does not work for me yet - sorry - I will try to further debug this - I am a
bit short with time though - will see - maybe I make my config public
at some point (so that others can see - and hopefully point me in the
right direction)

I am using river as packaged by nickh for debian bookworm
https://www.ne.jp/asahi/nickh/debian/

and chromium for debian trixie/testing

and basically my old configuration - that worked for me w/ sway,
just now with the wlroots binary

thanks so far.

-A

**Comment by k0kubun** [comment]
sway and wlroots might report application names differently, so if you used the config for sway as is, it might be why.

Could you run xremap with `RUST_LOG=debug xremap`, press something that is not working as expected, and share the entire output of the command as well as the config used for it?

**Comment by reuleaux** [comment]
Thanks, and sorry for not responding earlier:

(and I am CC'ing to Nick Hastings, who in the past was so kind
to help me get started with river, and who has provided the debian river
package that I am using)

@Nick: xremap (not yet working for me) is the one show stopper for
me to use river. (there are other things river, that I yet have to learn
- but more about those later).

... hoping to get him interested in this xremap stuff [?] - thanks in advance, Nick!


so I have two different xremaps installed (unpacked i.e.)

one that I use for sway (the sway binary i.e.):
```
/home/rx/opt/xremap/xremap
```

and another one for river (the wlroots-binary):
```
/home/rx/opt/xremap-wlroots/xremap
```

and below you can find my complete xremap config file:
I have line-at-a-time-scrolling on f1 and f2 - many people
have criticised me for this (f1 is for help!) - but that's what I am used
to, and what I like therefore

@Nick: xremap allows me to have more emacs-like keybindings for
chromium/firefox - and this works for me with sway (using the
sway-binary), but not with river (using the wlroots-binary).



now when I use xremap with sway (the /home/rx/opt/xremap/xremap) with
debugging on (as you suggested, k0kubun - thanks):

```
RUST_LOG=debug /home/rx/opt/xremap/xremap /home/rx/cfg/xremap/my.yml
```

scrolling with f1/ f2 works fine, and I I can see in the logs

```
 ...
 [2023-10-08T21:09:55Z DEBUG xremap::event_handler] => 1: KEY_F1
 $SWAYSOCK is not set. Defaulting to "/run/user/1000/sway-ipc.1000.291844.sock"
 application-client: Sway (supported: true)
 application: chromium
 [2023-10-08T21:09:55Z DEBUG xremap::action_dispatcher] 1: KEY_DOWN
 [2023-10-08T21:09:55Z DEBUG xremap::action_dispatcher] 0: KEY_DOWN
 [2023-10-08T21:09:55Z DEBUG xremap::event_handler] => 0: KEY_F1
 [2023-10-08T21:09:55Z DEBUG xremap::action_dispatcher] 0: KEY_F1
 ...
```

If I do the same in river (with the wlroots binary)

```
RUST_LOG=debug /home/rx/opt/xremap-wlroots/xremap /home/rx/cfg/xremap/my.yml
```

(if I press f1 i.e.) I get

```
 ...
 /dev/input/event10: HDA Intel PCH Headphone Mic
 /dev/input/event11: HDA Intel PCH Line Out
 /dev/input/event12: HDA Intel PCH HDMI/DP,pcm=3
 /dev/input/event13: HDA Intel PCH HDMI/DP,pcm=7
 /dev/input/event14: HDA Intel PCH HDMI/DP,pcm=8
 /dev/input/event2 : Dell AIO WMI hotkeys
 /dev/input/event3 : Sleep Button
 /dev/input/event4 : Power Button
 /dev/input/event5 : Power Button
 /dev/input/event6 : Dell WMI hotkeys
 /dev/input/event7 : PC Speaker
 /dev/input/event8 : Video Bus
 /dev/input/event9 : HDA Digital PCBeep
 ------------------------------------------------------------------------------
 Selected keyboards automatically since --device options weren't specified:
 ------------------------------------------------------------------------------
 /dev/input/event0 : AT Translated Set 2 keyboard
 ------------------------------------------------------------------------------
 [2023-10-08T21:05:09Z DEBUG xremap::event_handler] => 0: KEY_ENTER
 [2023-10-08T21:05:09Z DEBUG xremap::action_dispatcher] 0: KEY_ENTER
 [2023-10-08T21:05:13Z DEBUG xremap::event_handler] => 1: KEY_F1
 Could not find wayland compositor
 application-client: wlroots (supported: false)
 [2023-10-08T21:05:13Z DEBUG xremap::action_dispatcher] 1: KEY_F1
 [2023-10-08T21:05:14Z DEBUG xremap::event_handler] => 0: KEY_F1
 [2023-10-08T21:05:14Z DEBUG xremap::action_dispatcher] 0: KEY_F1
 ...
```

I cannot make much sense of this: except that I see "wlroots (supported:
false)", of course

Many thanks.
-Andreas


my config file /home/rx/cfg/xremap/my.yml
--------------------
```
# -*- mode: conf-colon -*-
keymap:
  - name: Blah
    application:
      only: [/^chromium/,Firefox-esr]
    remap:
      f1: { with_mark: down }
      f2: { with_mark: up }

      C-v: { with_mark: pagedown }
      M-v: { with_mark: pageup }

      C-a: { with_mark: home }
      C-e: { with_mark: end }

      Shift-C-a: { with_mark: C-a }

      M-Shift-comma: { with_mark: C-home }
      M-Shift-dot: { with_mark: C-end }

      C-k: [Shift-end, C-x, { set_mark: false }]

      C-g: [esc, { set_mark: false }]

      C-s: [C-f, f3]
      C-r: [C-f, Shift-f3]

      Super-Shift-r: f5

      Super-M-right: C-tab
      Super-M-left: Shift-C-tab

      C-Super-M-left: C-Shift-pageup
      C-Super-M-right: C-Shift-pagedown
      C-x:
        remap:
          C-f: C-o
          C-s: C-s
```

**Comment by k0kubun** [comment]
> Could not find wayland compositor

This seems like the problem.

The error message seems to come from [this wayland-client code](https://github.com/Smithay/wayland-rs/blob/8581b9d298e3bfc872a598380a09eb386a9db408/wayland-client/src/conn.rs#L267).

It appears that they expect environment variables like `WAYLAND_SOCKET` or `WAYLAND_DISPLAY` (+ `XDG_RUNTIME_DIR`) to be set. I suspect River may be one of the environments that don't set it (ref: https://github.com/Smithay/wayland-rs/issues/282).

Can you check if your environment has `XDG_RUNTIME_DIR` environment variable? If it does, it's worth trying setting `WAYLAND_DISPLAY=wayland-0` environment variable to xremap. If it doesn't, try `ls /run/user/*/wayland-*` and set that path to `WAYLAND_SOCKET` environment variable.

cc: @meowcoder (https://github.com/k0kubun/xremap/pull/345) Let me know if you have any other things we could try.

**Comment by meowcoder** [comment]
@k0kubun 
Nothing I can think of that you haven't covered already, save for updating river and possibly wlroots.

I can't reproduce the issue myself with riverwm/river@7f30c655c75568ae331ed0243578d91870f3f9c6 and wlroots 0.16.
Without `XDG_RUNTIME_DIR`, that points to an absolute path, river refuses to start and it properly sets the `WAYLAND_DISPLAY` variable, so xremap has no problem connecting to the socket in my case.
