### ISSUE TITLE
On hyprland input just get voided so no access

### ISSUE THREAD

**Issue by kawaegle** [k0kubun/xremap#246]
as title say, when I start it on hyprland (with sudo and without, and with systemctl --user or at the start of hyprland) all input are get but the keyboard just doesn't react at all

**Comment by k0kubun** [comment]
Can you share the entire output of the xremap command when the issue is reproducing?

**Comment by kawaegle** [comment]
config.py
```python
from xremap.dsl import *

define_modmap({
    'CapsLock': 'Control_L',
})
```


output (error because I need to force reboot)
```
Selecting devices from the following list:
------------------------------------------------------------------------------
/dev/input/event0 : Power Button
/dev/input/event1 : Lid Switch
/dev/input/event10: HD-Audio Generic HDMI/DP,pcm=7
/dev/input/event11: HD-Audio Generic HDMI/DP,pcm=8
/dev/input/event12: HD-Audio Generic Mic
/dev/input/event13: HD-Audio Generic Headphone
/dev/input/event14: AT Translated Set 2 keyboard
/dev/input/event2 : Video Bus
/dev/input/event3 : AT Translated Set 2 keyboard
/dev/input/event4 : PC Speaker
/dev/input/event5 : GXTP7863:00 27C6:01E0 Mouse
/dev/input/event6 : GXTP7863:00 27C6:01E0 Touchpad
/dev/input/event7 : Huawei WMI hotkeys
/dev/input/event8 : HD Camera: HD Camera
/dev/input/event9 : HD-Audio Generic HDMI/DP,pcm=3
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
Failed to grab device 'AT Translated Set 2 keyboard' at '/dev/input/event3' due to: Device or resource busy (os error 16)
------------------------------------------------------------------------------
/dev/input/event14: AT Translated Set 2 keyboard
------------------------------------------------------------------------------
```
config.yaml
```yaml
keymap: []
modmap:
- name: xremap-python
  remap:
    CapsLock: Control_L
```

**Comment by k0kubun** [comment]
The fact that there are a couple of `AT Translated Set 2 keyboard` devices, event14 appears to be the lastly added device while event3 seems to be added fairly early and original, and event3 is already grabbed, seems suspicious. 

Do you know what might be grabbing event3 (and possibly copying it to event14)? Only a single process could grab a device, and it's possible that event3 needs to be grabbed by xremap, stopping another process that's controlling it.

I guess it's one of the following situations:

* There's some application that remaps (or could remap) keys and is already taking its ownership through event3.
  * Or is this something common in Hyperland? @chenzaichun 
* It's something specific to the device driver for the `AT Translated Set 2 keyboard`
  * You may try the same thing with another keyboard, specifying only that through `--device` option.

It's something I can't reproduce and help you unless you figure out what's different/unexpected in your environment, or somehow report how to reproduce it on my X11 Ubuntu environment with an arbitrary keyboard. It'd be nice if you can provide that kind of information by trying different combinations of devices, running processes, X11 vs Wayland, different WMs, or OS.

---

It might be also useful to start xremap with `RUST_LOG=debug xremap ...` and see the output of that command. If it shows a different output, it'd be nice if you can share it here.

**Comment by luigir-it** [comment]
I’m on hyprland and I have the same issue. The log doesn’t seem to be useful.
![47B80AF7-3293-4782-8D84-1A8CB03173BD](https://user-images.githubusercontent.com/64033455/219881480-a5889a8d-3090-4dd5-93f0-3d78c8fd9c80.jpeg)

If I spam any keys, they are correctly shown in the output, but the keyboard does not work.

**Comment by k0kubun** [comment]
Ah, actually, it reminds me of a Wayland-specific issue, https://github.com/k0kubun/xremap/issues/105. 

If this is the case, it might be worth trying to start xremap with `sleep 1; xremap ...`, releasing an Enter key within 1 second.

**Comment by k0kubun** [comment]
So, I got a similar report outside this issue. They said it used to work under the same setup, and suspected something might have changed in evdev recently. They use Arch Linux, so it's understandable that things could be updated to a bleeding-edge version.

Which OS distribution do you use? Do both of you use Arch Linux as well?

**Comment by alyanser** [comment]
Got the same issue and yes, I'm using Arch (hyprland). Everything was perfect yesterday but woke up to this :(

```
(staz @ ~) $ sudo xremap ~/.config/xremap/config.yml --device /dev/input/event14
Selecting devices from the following list:
------------------------------------------------------------------------------
/dev/input/event0 : Lid Switch
/dev/input/event1 : Power Button
/dev/input/event10: HDA Intel HDMI HDMI/DP,pcm=8
/dev/input/event11: HDA Intel PCH Mic
/dev/input/event12: HDA Intel PCH Headphone
/dev/input/event13: SynPS/2 Synaptics TouchPad
/dev/input/event14: SINO WEALTH Gaming KB
/dev/input/event15: SINO WEALTH Gaming KB  System Control
/dev/input/event16: SINO WEALTH Gaming KB  Consumer Control
/dev/input/event17: SINO WEALTH Gaming KB  Keyboard
/dev/input/event2 : Power Button
/dev/input/event3 : AT Translated Set 2 keyboard
/dev/input/event4 : Video Bus
/dev/input/event5 :   HID Gaming Mouse
/dev/input/event6 :   HID Gaming Mouse Keyboard
/dev/input/event7 : Ideapad extra buttons
/dev/input/event8 : HDA Intel HDMI HDMI/DP,pcm=3
/dev/input/event9 : HDA Intel HDMI HDMI/DP,pcm=7
------------------------------------------------------------------------------
Selected devices matching ["/dev/input/event14"]:
------------------------------------------------------------------------------
/dev/input/event14: SINO WEALTH Gaming KB
```

After that, the keyboard goes unresponsive entirely. Tried it without the `--device` option, same result.

config.yml:
```
modmap:
  - name: capslock as control and escape
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Esc
        alone_timeout_millis: 500

keymap:
  - name: swap asciitilde with grave
    remap:
      Shift-grave: grave
      grave: shift-grave
```

**Comment by luigir-it** [comment]
> Which OS distribution do you use? Do both of you use Arch Linux as well?

I use EndeavourOs that is basically Arch afaik
Using `sleep 1; xremap` and pressing Enter during that second, does not solve the issue.

**Comment by antonamurskiy** [comment]
I'm having the same issue. :( (also arch + hyprland)

**Comment by k0kubun** [comment]
Another folk reported the same issue, and they said the following packages were relevant:

```
Package (3)              Old Version  New Version  Net Change

core/systemd             252.4-2      253-1          0.41 MiB
core/systemd-libs        252.4-2      253-1          0.07 MiB
core/systemd-sysvcompat  252.4-2      253-1          0.00 MiB
```

They said downgrading those packages to 252.4-2 makes xremap work again. I'm going to investigate this, but can you all confirm the same thing in your environment?

**Comment by kawaegle** [comment]
I'm not sure why but I've downgrade systemd and retry after a reboot.

Now it work but sometime

**Comment by antonamurskiy** [comment]
@k0kubun Appreciate all the work on this! Love the app, excited to use it again once it's back to normal.
In the meantime for the other folks who are having issues and are using hyprland, I just figured out that you can do the basic remaps in the hyprland config. You can't do the fancy stuff that xremap is capable of, but at least my capslock is ctrl again and that's good enough for the time being.

**Comment by alyanser** [comment]
> They said downgrading those packages to 252.4-2 makes xremap work again. I'm going to investigate this, but can you all confirm the same thing in your environment?

Yes! Downgrading systemd to 252.4-2 makes xremap work perfectly fine.

**Comment by threddast** [comment]
I'm having the same problem on EndeavourOS with Plasma wayland, so definitely not an hyprland-only problem

**Comment by acheronfail** [comment]
Yeah, upgraded my system (i3 on X11, with Arch) and had this problem. 

I can confirm that downgrading to system 242.4 has fixed it for me too!

**Comment by timothymiller** [comment]
@kawaegle Start from `exec-once = xremap /home/kawaegle/.config/xremap.yml &` _does not_ work for me.

Running the same command from any terminal works without `sudo` for me because I added my user to the input group.

Does it work for you?

**Comment by andreasaronsson** [comment]
I am on Arch with Gnome and I get permission denied after upgrading systemd to systemd-253-1

Downgrading to
systemd-252.2-4
is a workaround that works for me.

**Comment by kawaegle** [comment]
> Edit: It works if you run it as a systemd service.
> 
> 
> @kawaegle Start from `exec-once = xremap /home/kawaegle/.config/xremap.yml &` _does not_ work for me.
> 
> Running the same command from any terminal works without `sudo` for me because I added my user to the input group.
> 
> Does it work for you?

As I said on my edit bis, After some work and look around it work event started from  the exec once on hyprland and with the user systemd.

**Comment by luigir-it** [comment]
> So for a temporary workaround, in hypr.cfg:
> 
> ```
> input {
>   kb_options=caps:ctrl_modifier
> }
> ```

Hi. I  tried with kb_options but it didn´t work. Where did you find the right name for caps, ctrl_modifier and also other keys?

**Comment by antonamurskiy** [comment]
@luigir-it it accepts any XKB parameter so search that

**Comment by kohane27** [comment]
I'm running Arch and Sway(Wayland). Suddenly I realized `xremap` wasn't working. To supplement what others have found, simply downgrading `systemd` works:

```
$ systemctl --version
systemd 253 (253-1-arch)
```

To owngrade `systemd`:

```
$ sudo downgrade systemd
warning: downgrading package systemd (253-1 => 252.4-2)

Package (1)  Old Version  New Version  Net Change

systemd      253-1        252.4-2       -0.41 MiB

Total Installed Size:  28.34 MiB
Net Upgrade Size:      -0.41 MiB

:: Proceed with installation? [Y/n]
```

Reboot and `xremap` working again. Thanks guys!

**Comment by k0kubun** [comment]
Rumor says https://github.com/k0kubun/xremap/commit/2603e89999a25f6d65d2bce388ddb6f387101416 would fix the problem. I released that as v0.8.2. Can you try that version?

**Comment by kohane27** [comment]
@k0kubun  Thank you for your prompt fix!
I tested on `systemd 253 (253-1-arch)` and `xremap v0.8.2`. Reboot and this issue is gone. Thank you again!

**Comment by k0kubun** [comment]
That's fair. Maybe mouse scrolling should be enabled by default again and we should add an option to disable it with something like `mouse_scrolling: false` at the top level of a config. Would you be interested in writing a pull request to add that?
