### ISSUE TITLE
kde wayland

### ISSUE THREAD

**Issue by N4tus** [k0kubun/xremap#250]
Is there support to use xremap on kde with wayland?

**Comment by k0kubun** [comment]
First off, it should already work except for `application` filter. If you're not interested in using `application` filtering, you should have no problem with it.

If you do have interest in using `application` filter, we'd have to find a protocol to make that happen. Wayland is unfortunately still too immature to have that capability at that layer. So we rely on another layer on top of it. We currently target individual composers, but it's planned to switch Sway and Hypr to use wlroots protocol instead. Many Wayland composers use wlroots protocol and it seems like `application` filter can be implemented with that protocol.

However, some composers like GNOME don't use wlroots. I'm not sure if KDE uses wlroots, but I suspect it might not. Do you know of any protocol used by KDE with Wayland that could power `application` filter?

**Comment by N4tus** [comment]
Yes KDE does not use wlroots. There are interfaces that allow applications to communicate with kwin, but I do not know what you can do with them and how to interact with it.

**Comment by N4tus** [comment]
After digging for some protocols [`org_kde_plasma_window_management`](https://github.com/KDE/plasma-wayland-protocols/blob/master/src/protocols/plasma-window-management.xml) seems like a promising candidate, especially the `org_kde_plasma_activation_feedback` interface.

**Comment by k0kubun** [comment]
Nice. Would you be interested in working on a PR to support it?

**Comment by RedBearAK** [comment]
I subscribed to this issue even though I don't really have anything to contribute yet. I'm also interested in finding out if there is a way to get the window class and name/title in KDE while using Wayland. Information online regarding this is limited. 

I've been able to successfully connect to two different GNOME extensions via D-Bus from a Python app to get this information in Wayland. If it's being presented by some D-Bus interface in Plasma, the same thing should be possible with a Plasma script. 

These look interesting, but I don't know if this protocol just provides event signals or would actually be able to provide the window title and application class/name/id. 

```xml

    <event name="title_changed">
      <description summary="window title has been changed">
        This event will be sent as soon as the window title is changed.
      </description>
      <arg name="title" type="string" summary="window title"/>
    </event>

    <event name="app_id_changed">
      <description summary="application identifier has been changed">
        This event will be sent as soon as the application
        identifier is changed.
      </description>
      <arg name="app_id" type="string"/>
    </event>

```

And this part, although I'm bothered by the "only one client can bind to this interface at a time" part. 

```xml
  <interface name="org_kde_plasma_window_management" version="16">
    <description summary="application windows management">
      This interface manages application windows.
      It provides requests to show and hide the desktop and emits
      an event every time a window is created so that the client can
      use it to manage the window.

      Only one client can bind this interface at a time.
    </description>

    <enum name="state">
      <entry name="active" value="1 &lt;&lt; 0"/>
```

Here is a conversation with an AI that might shed some light: 

> Is there a way to get the class (like WM_CLASS in X11) and name/title (like WM_NAME in X11) from a D-Bus interface in Plasma while using Wayland? 

_Yes, it is possible to get the class and name/title of a window using a D-Bus interface in Plasma while using Wayland. In Wayland, this information is provided by the xdg-shell protocol, which is used to create and manage windows in the desktop environment._

_To get the class and name/title of a window using D-Bus, you can use the org.kde.KWin interface, which is provided by the KWin window manager used in the Plasma desktop environment. This interface provides a number of methods for interacting with windows, including methods for getting information about windows._

_To get the class of a window, you can use the org.kde.KWin.WindowInterface.Class method. This method takes the window ID as an argument and returns the window class as a string._

_To get the name/title of a window, you can use the org.kde.KWin.WindowInterface.Name method. This method takes the window ID as an argument and returns the window name/title as a string._

_Note that you will need to have permissions to access the org.kde.KWin interface on the D-Bus system bus in order to use these methods._

***

> How would I get the `window_id` of the active window, in KDE Plasma, in Wayland? Update the examples for both Python and Rust. 

_To get the window_id of the active window in KDE Plasma on Wayland, you can use the activeWindow method of the org.kde.KWin D-Bus interface._

***

These may or may not be working examples of how to do this. 

Python: 

```py
import dbus

bus = dbus.SessionBus()
kwin = bus.get_object('org.kde.KWin', '/org/kde/KWin')

# Get the active window ID
window_id = kwin.activeWindow()

# Get the window class
window_class = kwin.windowInterface().Class(window_id)

# Get the window name
window_name = kwin.windowInterface().Name(window_id)

print('Active window ID:', window_id)
print('Window class:', window_class)
print('Window name:', window_name)
```

Rust: 

```rs
extern crate dbus;

use dbus::{BusType, Connection};
use dbus::message::MatchRule;
use std::time::Duration;

fn main() {
    let conn = Connection::get_session_bus().unwrap();
    let kwin = conn.with_proxy("org.kde.KWin", "/org/kde/KWin", Duration::from_millis(5000));

    // Get the active window ID
    let window_id: u32 = kwin.method_call("org.kde.KWin", "activeWindow", ()).unwrap();

    // Get the window class
    let window_class: String = kwin.method_call("org.kde.KWin.WindowInterface", "Class", (window_id,)).unwrap();

    // Get the window name
    let window_name: String = kwin.method_call("org.kde.KWin.WindowInterface", "Name", (window_id,)).unwrap();

    println!("Active window ID: {}", window_id);
    println!("Window class: {}", window_class);
    println!("Window name: {}", window_name);
}
```

**Comment by RedBearAK** [comment]
Some notes. 

Here's a D-Bus query using `dbus-send` that has produced some output on Kubuntu: 

```
dbus-send --session --dest=org.kde.KWin --type=method_call --print-reply /KWin org.kde.KWin.queryWindowInfo
```

This should be translatable into something that can be used with the `dbus` module/crate in Python or Rust. 

Inside the array that comes back are some relevant entries: 

```
string "caption"
variant        string "Window Title"

string "resourceClass"
variant        array of bytes "Application Class"

string "resourceName"
variant        array of bytes "Application ClassName"
```

Here "Window Title", "Application Class" and "Application Class Name" are just placeholders for what is actually displayed there. 

Apparently "caption" is what you'd find in `WM_NAME` in X11, and "resourceClass" and "resourceName" together are the pair of strings you'll find in WM_CLASS in X11. The string for "resourceClass" and "resourceName" will often be the same, in my experience, but not always. 

This hasn't been tested yet under a Wayland session, to see if the same information is still available under the same labels, or at all.

**Comment by N4tus** [comment]
The events `title_changed` and `app_id_changed` are part of the interface `org_kde_plasma_window` and it states that only one client can be bound to it. The protocol `plasma_window_management` also defines two more interfaces named `org_kde_plasma_activation_feedback` and `org_kde_plasma_activation`, both do not have this restriction:
```xml
<interface name="org_kde_plasma_activation_feedback" version="1">
    <description summary="activation feedback">
      The activation manager interface provides a way to get notified
      when an application is about to be activated.
    </description>

    <request name="destroy" type="destructor">
      <description summary="destroy the activation manager object">
        Destroy the activation manager object. The activation objects introduced
        by this manager object will be unaffected.
      </description>
    </request>

    <event name="activation">
      <description summary="notify that an app is starting">
        Will be issued when an app is set to be activated. It offers
        an instance of org_kde_plasma_activation that will tell us the app_id
        and the extent of the activation.
      </description>
      <arg name="id" type="new_id" interface="org_kde_plasma_activation"/>
    </event>
  </interface>

  <interface name="org_kde_plasma_activation" version="1">
    <request name="destroy" type="destructor">
      <description summary="destroy the org_kde_plasma_activation object">
        Notify the compositor that the org_kde_plasma_activation object will no
        longer be used.
      </description>
    </request>

    <event name="app_id">
      <description summary="Offers the app_id"></description>
      <arg name="app_id" type="string" summary="application id, as described in xdg_activation_v1"/>
    </event>

    <event name="finished">
        <description summary="Notifies about activation finished, either by activation or because it got invalidated"></description>
    </event>
  </interface>
```

I am by  no means an expert, but if I understand the descriptions correctly the `activation` event should be emitted every time a window is activated (eg. gains focus). The event provides a id for an object with the `org_kde_plasma_activation` interface and it tells you the app_id, you can use to query additional information such as its title.

------

KWin does have dbus interface and it has a method `getWindowInfo` that can be used to extract the caption of a window given its uuid. 
This is an example output directly taken from QDBusViewer:
```
[Argument: a{sv}
{
"activities" = [Variant(QStringList): {"a252a281-f04e-4802-8d0f-10037df878d1"}],
"caption" = [Variant(QString): "QDBusViewer"],
"clientMachine" = [Variant(QString): ""],
"desktopFile" = [Variant(QString): "qdbusviewer-qt5"],
"desktops" = [Variant(QStringList): {"8f004922-2a5a-44f3-80e2-21a4efea6437"}],
"fullscreen" = [Variant(bool): false],
"height" = [Variant(double): 719], "keepAbove" = [Variant(bool): false],
"keepBelow" = [Variant(bool): false],
"localhost" = [Variant(bool): true],
"maximizeHorizontal" = [Variant(int): 0],
"maximizeVertical" = [Variant(int): 0],
"minimized" = [Variant(bool): false],
"noBorder" = [Variant(bool): false],
"resourceClass" = [Variant(QString): "qdbusviewer-qt5"],
"resourceName" = [Variant(QString): "qdbusviewer-qt5"],
"role" = [Variant(QString): ""],
"shaded" = [Variant(bool): false],
"skipPager" = [Variant(bool): false],
"skipSwitcher" = [Variant(bool): false],
"skipTaskbar" = [Variant(bool): false],
"type" = [Variant(int): 0],
"uuid" = [Variant(QString): "{f4ec79aa-8b95-4619-a284-c9b5e34b47d7}"],
"width" = [Variant(double): 821],
"x" = [Variant(double): 1000],
"y" = [Variant(double): 87]}
]
```
But I have not found a way to get the uuid from the active window. The uuid for this call was extracted from a similar method named `queryWindowInfo` which provides the same information for the current application (it does not take an argument.)  

But there is also the `org.kde.KWin.Scripting` interface, which would allow to execute a custom kwin script, which may be able to retrieve this information.

**Comment by N4tus** [comment]
After looking through all unstable kde wayland protocols, I have not found a way to get/create an object id for an object using any of the interface mentioned above, and they are not globals either. I am currently thinking, that this protocol is not actually implemented and thus the only choice is to use kwin script to gather this information. The only mention of this interface I could find was on [r/wayland](https://www.reddit.com/r/wayland/comments/oopz05/how_to_get_currentactive_window_title/).

[This stack exchange](https://unix.stackexchange.com/questions/706477/is-there-a-way-to-get-list-of-windows-on-kde-wayland) shows how to get the titles of all windows via a kwin script that is called via the dbus-interface. But I have never done any kwin scripting so someone else would need to continue from here.

**Comment by RedBearAK** [comment]
@N4tus 

> only choice is to use kwin script to gather this information

I agree that this seems like it will be necessary. Very similar to the need for a shell extension in GNOME. I was able to get something to print out in the terminal from a KWin script using `print(workspace.activeClient)`. It appeared to be something they call "application_id", which may lead to being able to get a "window_id", which might possibly be able to get attributes like `name`, `caption` or `class` from `getWindowInfo`. But it's all very murky at this point. 

The API documentation for KWin scripting did not help me at all. It appears to be written by, and written for, a computer, or at least someone who is already very familiar with API programming and/or the KDE project. It's very cryptic. 

There was a Reddit user who made a KWin script for me in the past for a moderate fee, to bring true "application switching" (like macOS or stock GNOME) to Plasma. They did a good job, and they have several other KWin scripts on the KDE Store. Maybe they would be open to another paid collaboration project to produce a KWin script that grabs the active window attributes and advertises them on a D-Bus interface, just like the GNOME extensions. 

https://store.kde.org/u/nclarius
https://github.com/nclarius

This is where I found a short Python script and a JavaScript stub that gets the application names. 

https://github.com/Ashark/Ashark-bin/

It's `get_list_of_windows` and `list_windows.js` that I tried to use. 

I am also very unfamiliar with KWin scripting, so not sure how much further I can get anytime soon.

**Comment by N4tus** [comment]
After some experimentation i actually have a working prototype fro kde on wayland https://github.com/N4tus/xremap/tree/kde-wayland.  
I don't know how stable this is and there are some caveats:
1. There has to be a kwin-script loaded. It only has 3 lines and a metadata.json (these are not part of my fork). The script makes a dbus call to xremap, which has an object server running in a separate thread (its the other way around for the gnome client) each time the active window changes. There is an dbus API for loading kwin-scripts, but I was unable to get that to work.
2. Since xremap creates a connection to the session bus it cannot be run as root.
3. I am using the resourceClass (other candidates are the caption and the resourceName) for application matching, but the casing is not consistent with x11 and kde on x11.  For example:

| application | `wmctrl -x -l` (on x11) | resourceClass (on x11) |resourceName (on x11) | resourceClass (on wayland) |resourceName (on wayland) |
| ---------------- | ------------------------------ | ----------------------------------------------- | ----------------------------------------------------- | ----------------------------------------------- | ----------------------------------------------------- |
| Alacritty | Alacritty.Alacritty | alacritty | alacritty | Alacritty | alacritty |
| QDBusViewer | qdbusviewer-qt5.QDBusViewer | qdbusviewer | qdbusviewer-qt5 | qdbusviewer | qdbusviewer-qt5 |
| Firefox | Navigator.firefox | firefox | navigator | firefox | firefox |

The resourceClass seems to be the same (ignoring casing) between x11 and wayland. But the resourceName is sometimes completely different.

kwin-script:
```js
workspace.clientActivated.connect(function(client){
     callDBus("com.k0kubun.Xremap", "/com/k0kubun/Xremap", "com.k0kubun.Xremap", "NotifyActiveWindow", client.caption, client.resourceClass, client.resourceName);
});
```
manifest:
```json
{
  "KPlugin": {
    "Name": "Xremap-Kwin",
    "Description": "The accompaning kwin script for xremap on kde",
    "Icon": "preferences-system-windows",
    "Authors": [
      {
        "Email": "username@gmail.com",
        "Name": "Firstname Lastname"
      }
    ],
    "Id": "xremap-kde",
    "ServiceTypes": [
      "KWin/Script"
    ],
    "Version": "1.0",
    "Licsense": "GPLv2+",
    "Website": "https://github.com/xremap/xremap-kde"
  },
  "X-Plasma-API": "javascript",
  "X-Plasma-MainScript": "code/main.js"
}

```

**Comment by N4tus** [comment]
I figured out how to load a script via the dbus api, so ill be using this instead of a fully fledged kwin-script. This also means that I don't need the metadata.json anymore.

**Comment by k0kubun** [comment]
I can release the `kde` binary if you make it a pull request. Would you be interested in it?

**Comment by N4tus** [comment]
I'll make a PR once i have fully implemented the loading of the kwin-script, as well as fixed a bug within the kwin-script itself.

**Comment by k0kubun** [comment]
completed in https://github.com/k0kubun/xremap/pull/264. thanks!
