### ISSUE TITLE
scancode help: xf86audioraisevolume vs volume?

### ISSUE THREAD

**Issue by BvngeeCord** [k0kubun/xremap#262]
I am attempting to switch my current confuration from xremap for key-to-key remaps *ontop* of [swhkd](https://github.com/waycrate/swhkd) for application macros, to just xremap, in order to reduce complexity and because swhkd has limitations. I am coming across some confusion though, related to volume/audio keys. In swhkd, as per [swhkd-keys.5.scd](https://github.com/waycrate/swhkd/blob/main/docs/swhkd-keys.5.scd), both `volumeup` aswell as `xf86audioraisevolume` and the related keys are supported. However, the latter doesn't seem to work in xremap. Swhkd also [uses](https://github.com/waycrate/swhkd/blob/main/swhkd/Cargo.toml#LL18C4-L18C4) the evdev crate, so it wouldn't make sense why xremap couldn't also use them. Maybe there's a core difference with the xf86audioxxxx keys that I'm not understanding? If so, please let me know. (I noticed that they are also not listed in [evdev/src/scancodes.rs](https://github.com/emberian/evdev/blob/1d020f11b283b0648427a2844b6b980f1a268221/src/scancodes.rs#L26-L572), which is confusing.) My keyboard (Glorious GMMK Pro) emits them via a scroll wheel, and I don't feel like messing with the firmware to change that.

**Comment by k0kubun** [comment]
Starting `RUST_LOG=debug xremap` and tapping a key that you want to remap with and without swhkd would help. It shows the key name that xremap recognizes.

**Comment by BvngeeCord** [comment]
I ran the command as you said, and it simply did not recognize anything. It recognizes all the other keypresses, but the volume wheel steps (which emit `xf86audioraisevolume` and `xf86audiolowervolume`) and presses (`xf86audiomute`) were not seen at all. I also forgot to mention, which is probably significant, that the `print` key is also not detected for me in xremap, where it is in swhkd. The equivalent debug mode for swhkd reports:
```
Hotkey {
            keybinding: KeyBinding {
                keysym: KEY_VOLUMEUP,
                modifiers: [],
                send: false,
                on_release: false,
            },
            command: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+",
        },
        Hotkey {
            keybinding: KeyBinding {
                keysym: KEY_VOLUMEDOWN,
                modifiers: [],
                send: false,
                on_release: false,
            },
            command: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-",
        },
        Hotkey {
            keybinding: KeyBinding {
                keysym: KEY_MUTE,
                modifiers: [],
                send: false,
                on_release: false,
            },
            command: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle",
        },
        Hotkey {
            keybinding: KeyBinding {
                keysym: KEY_SYSRQ,
                modifiers: [],
                send: false,
                on_release: false,
            },
            command: "grim -g \"$(slurp)\"",
        }
```
which is quite interesting, as it seems to parse my config (which uses the xf86audioxxxx names) as just regular volumeup/volumedown keys...

**Comment by k0kubun** [comment]
Hmm, interesting. Have you tried remapping `KEY_VOLUMEUP`, `KEY_VOLUMEDOWN`, `KEY_MUTE`, and `KEY_SYSRQ` on xremap? Also, maybe worth trying to start xremap with and without sudo, if that was not in sync with swhkd.

**Comment by BvngeeCord** [comment]
Well this is intersting. I just replaced the xf86audioxxxx keys for the regular volumeup/volumedown/mute keys in my swhkd config, and they produce the same parsed output in swhkd debug mode, and still are detected. So maybe there's just some translation layer or equivalence from the xf86audioxxxx keys to the volumeup/volumedown keys? still doesn't explain the `print` not being detected as there's no different version of it afaik

**Comment by BvngeeCord** [comment]
> Hmm, interesting. Have you tried remapping `KEY_VOLUMEUP`, `KEY_VOLUMEDOWN`, `KEY_MUTE`, and `KEY_SYSRQ` on xremap? Also, maybe worth trying to start xremap with and without sudo, if that was not in sync with swhkd.

Oh I just saw this. I will try that now

**Comment by k0kubun** [comment]
I wonder if there's a separate event device that emits those keycodes which swhkd grabs but xremap doesn't. Can you check which event devices your swhkd grabs?

**Comment by BvngeeCord** [comment]
I'm not very sure how to debug that. However, I can show that swhkd _does_ pickup more devices.

Swhkd debug:
	Attempting to find all keyboard file descriptors.
			**Keyboard: Glorious GMMK Pro Keyboard**
			**Keyboard: Glorious GMMK Pro Consumer Control**
	Other: Glorious GMMK Pro System Control
	Other: Glorious GMMK Pro Mouse
			**Keyboard: Glorious GMMK Pro**
	Other: FIFINE Microphones FIFINE K670 Microphone Consumer Control
	Other: Glorious Model O Wireless
	Other: Glorious Model O Wireless
			**Keyboard: Glorious Model O Wireless Keyboard**
	Other: Glorious Model O Wireless System Control
			**Keyboard: Glorious Model O Wireless Consumer Control**
	Other: Glorious Model O Wireless
			**Keyboard: Glorious GMMK Numpad Keyboard**
			**Keyboard: Glorious GMMK Numpad Consumer Control**
	Other: Glorious GMMK Numpad Mouse
			**Keyboard: Glorious GMMK Numpad**
	Other: UVC Camera (046d:0804)
	Other: HDA Intel PCH Front Headphone
	Other: HDA Intel PCH Line Out CLFE
	Other: HDA Intel PCH Line Out Surround
	Other: HDA Intel PCH Line Out Front
	Other: HDA Intel PCH Line
	Other: HDA Intel PCH Rear Mic
	Other: HDA Intel PCH Front Mic
	Other: HDA NVidia HDMI/DP,pcm=9
	Other: HDA NVidia HDMI/DP,pcm=8
	Other: HDA NVidia HDMI/DP,pcm=7
	Other: HDA NVidia HDMI/DP,pcm=3
	Other: Eee PC WMI hotkeys
	Other: PC Speaker
	Other: Power Button
	Other: Power Button
	Other: Sleep Button
	8 Keyboard device(s) detected.

xremap:
	/dev/input/event16: Glorious GMMK Pro
	/dev/input/event21: Glorious GMMK Pro Keyboard
	/dev/input/event22: Glorious GMMK Numpad
	/dev/input/event25: Glorious GMMK Numpad Keyboard
	/dev/input/event29: Glorious Model O Wireless Keyboard

Let me know if there's anything else you want me to look at, I'm not very familiar with the whole event system and how it works.

**Comment by k0kubun** [comment]
xremap has `--device` option to explicitly specify which devices to grab. Could you try selecting all of these with xremap? You can do things like `--device /dev/input/event16` if you want to be completely specific.

Also, just out of curiosity, which do you use, Wayland or X11? Which xremap binary distribution do you use for it?

**Comment by BvngeeCord** [comment]
Sorry it's been a bit, been busy with school. It is definitely as you suspected - adding the Consumer Control device manually fixed it completely, and the normal VolumeUp/Down, Mute, and SYSRQ (not Print tho) work perfectly. Turns out it was a simpler problem after all! Still not sure exactly where the xf86audioxxxx keys come from, but knowing that they don't seem to work differently that the other keys I'm not gonna worry about it. However I do think it is worth looking into why the Consumer Control devices weren't picked up automatically.

And I completely forgot to mention! I am on Hyprland, but there is no AUR package with the hyprland feature flag enabled yet so I just installed with cargo install.

**Comment by k0kubun** [comment]
:+1: I'm glad it's working now. 

> And I completely forgot to mention! I am on Hyprland, but there is no AUR package with the hyprland feature flag enabled yet so I just installed with cargo install.

Currently, the only AUR repository I know of is xremap-x11-bin, which I believe is maintained by @njkevlani at https://github.com/njkevlani/aur-autoupdater. If @njkevlani is open to sharing its ownership, I can co-maintain the repository (maybe under https://github.com/xremap if you're happy with it) and publish more variants as we add. @njkevlani WDYT?

**Comment by njkevlani** [comment]
> If @njkevlani is open to sharing its ownership, I can co-maintain the repository (maybe under https://github.com/xremap if you're happy with it) and publish more variants as we add.

Hey, I would be happy to do that :)

I was thinking about 2 approaches, we can use either of them:
1. Use https://github.com/njkevlani/aur-autoupdater itself and publish other packages as well.
2. Use some GitHub action to publish new packages to AUR. A quick google search shows a few GitHub actions, one of them is https://github.com/KSXGitHub/github-actions-deploy-aur.

Also, open to other approaches.
