### ISSUE TITLE
Publish more variants on AUR

### ISSUE THREAD

**Issue by k0kubun** [k0kubun/xremap#265]
moved from https://github.com/k0kubun/xremap/issues/262#issuecomment-1479207100 cc: @njkevlani @BvngeeCord 

> > If @njkevlani is open to sharing its ownership, I can co-maintain the repository (maybe under https://github.com/xremap if you're happy with it) and publish more variants as we add.
>
> Hey, I would be happy to do that :)
> 
> I was thinking about 2 approaches, we can use either of them:
> 1. Use https://github.com/njkevlani/aur-autoupdater itself and publish other packages as well.
> 2. Use some GitHub action to publish new packages to AUR. A quick google search shows a few GitHub actions, one of them is https://github.com/KSXGitHub/github-actions-deploy-aur.
>
> Also, open to other approaches.

**Comment by k0kubun** [comment]
As you suggested, I agree that it's probably nice to be able to just work on xremap binary in the repository, using a GitHub action or something else.

However, I'm thinking about completing the transition first with your aur-autoupdater and think about changing the tool afterwards. Does that make sense? And then the question is, do you want to use aur-autoupdater for non-xremap projects, or is it okay to use the repository as a place to publish xremap binary?

**Comment by njkevlani** [comment]
> I'm thinking about completing the transition first with your aur-autoupdater and working on changing the tool afterwards. Does that make sense?

Yes, that makes sense.

> do you want to use aur-autoupdater for non-xremap projects

I do not have plans for non-xremap projects yet.

> is it okay to use the repository as a place to publish xremap binary?

Yes, that is totally fine.

I'll work on adding support for publishing other xremap binaries this weekend.

**Comment by k0kubun** [comment]
Thanks :+1:

Would you mind transferring the aur-autoupdater repository to [xremap org](https://github.com/xremap)? If you want to keep it under your username, never mind. But having a repository under an organization would allow us to co-maintain credentials and other settings when necessary.

**Comment by k0kubun** [comment]
:+1: I sent you an invitation to join the org. When you have a chance, could you initiate the transfer to xremap org at https://github.com/njkevlani/aur-autoupdater/settings? I'll make you an admin on the repository again once transferred.

**Comment by njkevlani** [comment]
Done, https://github.com/xremap/aur-autoupdater.

**Comment by k0kubun** [comment]
Thank you! I'll see if I can publish binary for hyper from there.

**Comment by k0kubun** [comment]
I created https://aur.archlinux.org/packages/xremap-hypr-bin at https://github.com/xremap/aur-autoupdater/pull/10. @BvngeeCord Could you test the package when you have a chance?

@njkevlani I added you as a co-maintainer of xremap-hypr-bin on AUR. In case I need to fix something, could you add me (k0kubun) as a co-maintainer to xremap-x11-bin on AUR as well?

**Comment by njkevlani** [comment]
> could you add me (k0kubun) as a co-maintainer to xremap-x11-bin on AUR as well?

Done.

**Comment by BvngeeCord** [comment]
> @BvngeeCord Could you test the package when you have a chance?

Sure thing! I will update you when I test it, likely tonight once I get home. Thanks guys!

**Comment by BvngeeCord** [comment]
`xremap-hypr-bin` works perfectly. Thanks so much!!
