### ISSUE TITLE
BadWindow error on xmonad

### ISSUE THREAD

**Issue by garin** [k0kubun/xremap#29]
xmonad(http://xmonad.org/) でワークスペースを選択すると、BadWindow のエラーでセグフォが発生し、xremap が終了します。

``` console
% xremap ~/.xremaprc.rb
// 通常のウィンドウを選択しても問題はない
remapped for class: "mlterm"
remapped for class: "emacs"
// xmonad のワークスペース自体を選択
error detected! XErrorEvent(serial=811 error_code=3 request_code=15 minor_code=0 text=)
zsh: segmentation fault  xremap ~/.xremaprc.rb
```

C 言語に詳しくないので推測ですが、
XGetTextProperty が false の時は break の処理が入っていますが、その後でセグフォが発生しているようです。

https://github.com/k0kubun/xremap/blob/master/src/xlib_wrapper.c#L22

そこで、XGetTextProperty が 0 の時は強制的に関数から抜ける処理を追加しました。
display_obj を返すという変な処理になっていますが、ワークスペースを選択しても BadWindow のエラーで xremap が終了しなくなります。

https://github.com/garin/xremap/commit/5689be3b54739da61e8364a656c9d9aafd2646f7#diff-204275e5497156173fdf4d7dc2b89595R28

正しい対処方法があれば修正お願いします。

**Comment by k0kubun** [comment]
xmonadやbspwmを使用していないため私自身は確認できないのですが、お二人に動作確認いただいているということでそのままマージいたしました。ありがとうございます。

**Comment by garin** [comment]
@k0kubun 対応ありがとうございます！
69240e9 で問題なく動作するのを確認しました。

**Comment by yoshinari-nomura** [comment]
今日から Ubuntu 18.04 LTS を使いはじめた者です (これまでは Macです)．

よいキーリマッパが欲しくて，さっそくインストールしてみましたが，
以下の部分の `XGetTextProperty` が常に 0 を返しているようで， うまく動きません．

```c
  if (XGetTextProperty(display, window, &prop, net_wm_name) == 0) {
    return display_obj;
  }
```
コメントアウトしたら，うまく動作しました．
