### ISSUE TITLE
Lots of issues with 0.8.X on macbook m1, 0.8.5 doesnt work

### ISSUE THREAD

**Issue by derzahla** [k0kubun/xremap#291]
The latest version 0.8.5 does not work at all for me(gnome).  I get 'permission denied' to the input device when launching as my user and with sudo it causes me to lose control of track pointer (clicks still work)  and 'enter' key stops functioning.  Even before, I would have spotty luck with most version of 0.8.x - at times terminal would continually scroll as if enter was being held down, usually upon starting or restarting xremap or mappings would just randomly stop working.  I have switched back to 0.7.15 now and so far so good.  Would like to eventually find out what the problem is though

**Comment by k0kubun** [comment]
What's your OS distribution?

**Comment by derzahla** [comment]
sorry, its asahi(arch) linux

**Comment by k0kubun** [comment]
> I have switched back to 0.7.15 now and so far so good.

Can you identify which exact version was the last working version? Does each of v0.8.0, v0.8.1, v0.8.2, v0.8.3, and v0.8.4 work?

**Comment by k0kubun** [comment]
Also, can you show the entire log of xremap output when it's started?

**Comment by k0kubun** [comment]
Closing until the necessary information is provided.
