### ISSUE TITLE
Support Hyper Modifier

### ISSUE THREAD

**Issue by cheyngoodman** [k0kubun/xremap#296]
This was mentioned and closed here, but I'm not sure it properly understood or resolved: https://github.com/k0kubun/xremap/issues/261

In the code I see references to Super_L but I can't find anything for Hyper_L which I'd like to use as a separate modifier than Super. 

In both issues we wish to assign mod3 to be Hyper_L (66) or Hyper_R (135) and for that Hyper_L key to be bound to CapsLock or for the Hyper_R key to be bound to Ctrl_R.

Can this syntax be made valid?:
```yml
modmap:
  - remap:
      CapsLock: Hyper_L
  - remap:
      Ctrl_R: Hyper_R
  - remap:
      mod3: [Hyper_L, Hyper_R]
  - remap:
      mod4: [Super_L, Super_R]
```

Replicating that desired configuration in xmodmap looks like:
```
clear lock
clear control
clear mod3
clear mod4
keycode 66 = Hyper_L NoSymbol Hyper_L
keycode 105 = Hyper_R
add control = Control_L
add mod3 = Hyper_L Hyper_R
add mod4 = Super_L Super_R
```

My default xmodmap:
```
shift       Shift_L (0x32),  Shift_R (0x3e)
lock        Caps_Lock (0x42)
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Alt_L (0xcc),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3        ISO_Level5_Shift (0xcb)
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c)
```

The configured xmodmap:
```
shift       Shift_L (0x32),  Shift_R (0x3e)
lock      
control     Control_L (0x25)
mod1        Alt_L (0x40),  Alt_R (0x6c),  Alt_L (0xcc),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3        Hyper_L (0x42),  Hyper_R (0x69),  Hyper_R (0x87),  Hyper_L (0xcf)
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce)
mod5        ISO_Level3_Shift (0x5c)
```

- 0x69 went from Control_R to Hyper_R
- 0x42 went from Caps_Lock to Hyper_L
- mod3 became Hyper_L (0x42),  Hyper_R (0x69),  Hyper_R (0x87),  Hyper_L (0xcf)
- mod4 removed Hyper_L (0xcf) and became only Super_L (0x85),  Super_R (0x86),  Super_L (0xce)

Here's a reference to Hyper being a separate key than Super: [Space-Cadet Keyboard](https://en.wikipedia.org/wiki/Space-cadet_keyboard).

**Comment by k0kubun** [comment]
I didn't notice that they were different keys. I need to know the key code used in evdev, but I'm not sure how xmodmap's one maps to evdev's one. So I need your help to investigate that since my keyboard doesn't seem to have one.

Can you start xremap with `RUST_LOG=debug xremap`, press and release Super_L/R and Hyper_L/R one by one, and share the entire command output of xremap here? That should have a bunch of `KEY_*` outputs that are needed to support remapping those keys.

**Comment by cheyngoodman** [comment]
It looks like I have a misunderstanding of how the Hyper key works. It appears that evdev doesn't have a symbol for a physical Hyper key. I think the Hyper_L and Hyper_R I see are X11 specific and might not be in scope.

I found more information in a similar software's FAQ:  https://github.com/kmonad/kmonad/blob/fecdb828d042137115288b3150595c3b0791d039/doc/faq.md#q-how-do-i-emit-hyper_l

**Comment by k0kubun** [comment]
Thanks for finding that information. If my understanding of https://github.com/kmonad/kmonad/issues/22#issuecomment-678829937 is correct, kernel-level tools like xremap or kmonad should emit some Linux keycode, which is already possible, and then you need to instruct X11 to treat that as Hyper using something else. It's probably out of scope for xremap, so I'm closing this.

**Comment by simonwiles** [comment]
Do I have it right that this means I cant use `xremap` to assign the Capslock key as a modifier?  I use `.Xmodmap` to map my <kbd>Capslock</kbd> key to `HYPER_L` / `mod3`, and then `sxhkd` to assign actions to what is, in practice, <kbd>Capslock</kbd> + <kbd>F</kbd> etc.  Is it possible to do this (or the equivalent) with `xremap`?  I'd really like to replace everything with `xremap` (not least so it works across X11 and Wayland), but >90% of my use-cases are to map <kbd>Capslock</kbd> + something.

**Comment by cheyngoodman** [comment]
You can use this software to remap the capslock key to a different key, that key may also be a modifier like ctrl/alt/meta.

Hyper modifier isn't a key but can be a key configured as an X11 modifier if configured in Xmodmap.

That seems to be out of scope for the keyboard or keyboard software, but in scope for the X11 display server specifically.

**Comment by simonwiles** [comment]
Looking at this again after a good night's sleep I realize what I want is really the [`virtual_modifiers`](https://github.com/k0kubun/xremap#virtual_modifiers) section of the config -- for my purposes the `HYPER` business is a means to an end I can achieve probably better this way instead.  I think I'm on my way :)  Thank you!
