### ISSUE TITLE
Feature request: map one key to many mods

### ISSUE THREAD

**Issue by hab25** [k0kubun/xremap#298]
e.g., support
```json
{
  "modmap": [
    {
      "remap": {
        "rightalt": "control-leftalt-shift-super"
      }
    }
  ]
}
```

---
Use case: I have a lot of shortcuts using `rightalt` (which almost all my applications understand as `AltGr`), but [Emacs cannot (directly) use `AltGr` as a modifier](https://github.com/emacs-mirror/emacs/blob/31a80f61ec03bcbb79720c0dc640272aba160865/doc/emacs/custom.texi#L2030). As a workaround, I want to do the mapping in the example above. Currently, I can achieve this in practice by mapping each of the shortcuts manually, e.g. 
```json
{
  "keymap": [
    {
      "application": {
        "only": "Emacs"
      },
      "remap": {
        "rightalt-a": "control-leftalt-shift-super-a",
        "rightalt-b": "control-leftalt-shift-super-b",
        "rightalt-c": "control-leftalt-shift-super-c"
      }
    }
  ]
}
```
As I have many more than 3 shortcuts using `rightalt`, doing this is much more repetitive and error-prone than what the feature would enable.

**Comment by k0kubun** [comment]
Sounds good. I slightly prefer `"rightalt": ["control", "leftalt", "shift", "super"]` over `"rightalt": "control-leftalt-shift-super"`, but overall this idea makes sense.

I personally don't have a use case for this, but I'd be open to merging a pull request that adds this feature if anybody is interested in making one.

**Comment by jixiuf** [comment]
I remap my  spacebar with  [dual-function-keys](https://gitlab.com/interception/linux/plugins/dual-function-keys)  
1. tap for spacebar
2. hold for  `super+control+alt`

**Comment by k0kubun** [comment]
@jixiuf I've seen you recommended dual-function-keys in https://github.com/k0kubun/xremap/issues/290#issuecomment-1537276322 too, but I'm not sure how it helps xremap solve these issues. Do you use xremap and dual-function-keys together? If so, what is the missing feature that prevents you from using a single key remapper?

**Comment by k0kubun** [comment]
Thanks for your reply. I created another thread https://github.com/k0kubun/xremap/issues/306 for this discussion to avoid deviating this thread too much. Let's keep dual-function-keys -related conversations there instead of hinting that we need the feature in multiple other issues.

**Comment by k0kubun** [comment]
@jixiuf implemented this :tada: https://github.com/k0kubun/xremap/pull/339
