### ISSUE TITLE
Is it possible to run `xremap` on top of `kanata` for the same device?

### ISSUE THREAD

**Issue by kohane27** [k0kubun/xremap#305]
Hello @k0kubun, hope you're doing well.

## Description

I'm wondering if it's possible to run `xremap` on top of `kanata` for the same device. [kanata](https://github.com/jtroo/kanata) is similar to [kmonad](https://github.com/kmonad/kmonad) and I use `kanata` to implement home-row mod for my laptop keyboard `/dev/input/event4`. But `kanata` doesn't support application-specific remaps, so I'm hoping to use `xremap` to fill in the gaps.

1. Run `kanata` as a `systemd` service
2. Run `xremap` in the terminal, I get the following output:

```bash
➜  xremap /home/username/.config/xremap/config.yml
Selecting devices from the following list:
------------------------------------------------------------------------------
/dev/input/event4 : AT Translated Set 2 keyboard
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
Failed to grab device 'AT Translated Set 2 keyboard' at '/dev/input/event4' due to: Device or resource busy (os error 16)
```

The reason is that `kanata` is "using" `/dev/input/event4`. Is it possible to "share" `/dev/input/event4` among `kanata` and `xremap`?

## What I've tried

1. Run `kanata` as a systemd service
2. Run `sudo keyd` in the terminal, I get the following output:

```bash
✖  sudo keyd
CONFIG: parsing /etc/keyd/default.conf
Starting keyd v2.4.3 (5e4ef41)
DEVICE: ignoring 0fac:1ade  (keyd virtual pointer)
DEVICE: match    2333:6666  /etc/keyd/default.conf      (ydotoold virtual device)
DEVICE: match    0001:0001  /etc/keyd/default.conf      (kanata)
DEVICE: match    cb10:3156  /etc/keyd/default.conf      (Keebio The Nyquist Keyboard)
DEVICE: ignoring 0002:000a  (TPPS/2 Elan TrackPoint)
DEVICE: ignoring 0002:0007  (SynPS/2 Synaptics TouchPad)
EVIOCGRAB: Device or resource busy
DEVICE: WARNING Failed to grab /dev/input/event4
```

3. Run `keyd-application-mapper` in the terminal with `/home/username/.config/keyd/app.conf`:

```
[firefox]

control.semicolon = C-comma
control.w = C-backspace
control.p = up
control.n = down
```

4. Go to Firefox and the remap works even though `keyd` failed to grab `/dev/input/event4`.

## Conclusion

I understand this is a bit off-topic with the `keyd` bit, but it seems that sharing the same device for two key remappers are possible? I'd love to know what you think. Thank you again for creating `xremap`.

**Comment by k0kubun** [comment]
> Is it possible to "share" /dev/input/event4 among kanata and xremap?

xremap uses evdev's grab and I suspect kanata uses the same thing. `libevdev_grab` doesn't allow sharing the same device:

> https://www.freedesktop.org/software/libevdev/doc/latest/group__init.html#ga5d434af74fee20f273db568e2cbbd13f
> This prevents other clients (including kernel-internal ones such as rfkill) from receiving events from this device.

However, you could still run multiple such programs for a single device. xremap grabs a device to receive events, but it also spawns another device to emit events. If katana grabs the device created by xremap, then xremap and katana would effectively handle events from the same original device. You could let xremap grab a device created by katana if katana works in the same way, but whether it works that way or not is not under xremap's control.

**Comment by kohane27** [comment]
Thank you so much for checking the `libevdev` spec for me. I really appreciate it.

If anyone were in similar shoes (it should be similar if you're using `kmonad`), hopefully the following is helpful:

The rule is that we use `kanata` to grab `/dev/input/event4`, then we use `xremap` to grab `kanata`:

`/dev/input/event4` <- `kanata` <- `xremap`:

`~/.config/kanata/kanata.kbd`

```
(defcfg
  linux-dev /dev/input/by-path/platform-i8042-serio-0-event-kbd
)
```

Then run `xremap` like below:

```bash
xremap --device='kanata' --watch=device /home/username/.config/xremap/config.yml
```

You may have performance concern regarding running two keymappers on the same input device. Fortunately, for now, I have not noticed any input lag.

Cheers!
