### ISSUE TITLE
Dual function keys

### ISSUE THREAD

**Issue by k0kubun** [k0kubun/xremap#306]
Re: https://github.com/k0kubun/xremap/issues/290#issuecomment-1537276322, https://github.com/k0kubun/xremap/issues/298#issuecomment-1581965311

@jixiuf combines both xremap and [dual-function-keys](https://gitlab.com/interception/linux/plugins/dual-function-keys) to achieve:

1. tap for spacebar
2. hold for `super+control`

But we might be able to extend xremap's `held`/`alone` to support this.

---

As to macOS compatibility, we could add a script to convert an xremap YAML file into a Karabiner-Element config JSON file. It should, however, live in a separate repository, e.g. xremap/xremap-karabiner-elements.

**Comment by augustebaum** [comment]
I confirm both of these would be awesome.
Currently I am used Karabiner on my Mac to remap `space` to spacebar when tapped and `super+control+alt` when held -- I use this "hyper" key for managing my windows.
