### ISSUE TITLE
GNOME extension fails to appear in search/browse tab of Extension Manager

### ISSUE THREAD

**Issue by RedBearAK** [k0kubun/xremap#307]
I have no idea what is causing this issue. I'm unfamiliar with the apps and systems involved with how GNOME extensions are submitted and listed as compatible with a particular version of GNOME. 

For some time now I've been testing a project of mine in a number of different Linux distros with GNOME desktops. The most convenient way to quickly find and install GNOME extensions for quite a while now has been the relatively new "Extension Manager" app that can be installed from Flathub. 

```sh
flatpak install extensionmanager
```

Or...

```sh
flatpak install com.mattjakeman.ExtensionManager
```

Several times now, I've installed that app on a distro I'm testing (mostly in virtual machines using GNOME Boxes/QEMU) and searched for the `Xremap` extension, only to see "No Results Found", even though the Xremap extension supports that version of GNOME. This has happened on different versions of GNOME. 

In this app, you can choose "Show Unsupported" from the hamburger menu icon in the header bar. By doing this, the Xremap extension will finally appear. Normally unsupported extensions will have a gray button with "Unsupported" instead of a blue "Install" button. 

When the Xremap extension finally appears after selecting "Show Unsupported" from the menu, it has a blue "Install" button and can be installed. So the problem is that it just won't appear in searches without using the "Show Unsupported" option. Which is pretty strange. 

My theory is that there is something wrong with the metadata for the Xremap extension that the Extension Manager app uses to determine if extensions are "supported" by that version of GNOME. Something must be causing a glitch that keeps the Xremap extension from being available in the Browse tab without that option in the menu. 

This is affecting me because I'm using the Xremap extension as one of three different GNOME extensions I've discovered that provide the application class and window name/title over D-Bus, to allow the `keyszer` keymapper to work in Wayland+GNOME. The other two are "Focused Window D-Bus" and "Window Calls Extended". With those two extensions I've never had this issue with them not appearing when searching in Extension Manager. In fact I don't know that I've seen this problem with any other GNOME extension, with the extension clearly being compatible with that version of GNOME, but not showing up unless I enable "Show Unsupported". 

The issue with Xremap not showing up while searching seems to mostly happen with the newer versions of GNOME, like GNOME 44. On the other hand, with older versions of GNOME like 3.38.x on Zorin OS, the Xremap extension is the only one of the three that is compatible and appears in search. So my project can work in a Wayland session on Zorin OS only because of the Xremap extension, but frequently in the newer versions of GNOME the Xremap extension will appear to not exist, at least when trying to search for it from within this application. 

Note that the app I'm talking about is not the same as the older "Extensions" app, which does not have any kind of browse or search ability, but was just a way to enable or disable extensions.

**Comment by k0kubun** [comment]
Moving this to https://github.com/xremap/xremap-gnome/issues/4 since it doesn't seem like something that can be fixed in this repository.
