### ISSUE TITLE
Cannot autostart xremap by systemctl on Kubuntu 22.10

### ISSUE THREAD

**Issue by Thesoul20** [k0kubun/xremap#310]
I have write a server like:
```shell
[Unit]
Description=xremap aigo 87 keyboard 2023 
After=default.target

[Service]
Restart=always
ExecStart=/home/choose/.config/xremap/aigo87.sh
ReStartSec=60
StartLimitInterval=30
[Install]
WantedBy=default.target
```
the `aigo87.sh` is 
```shell
xremap /home/choose/.config/xremap/aigo87.yml --device /dev/input/event7
```
, and when run this sh file by the command: `bash /home/choose/.config/xremap/aigo87.sh` **working well**.

But when I check the status of the server, the information is:
```shell
× xremap.service - xremap aigo 87 keyboard 2023
     Loaded: loaded (/etc/systemd/system/xremap.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-06-23 08:21:19 CST; 1s ago
   Duration: 1ms
    Process: 4467 ExecStart=/home/choose/.config/xremap/aigo87.sh (code=exited, status=203/EXEC)
   Main PID: 4467 (code=exited, status=203/EXEC)
        CPU: 1ms

6月 23 08:21:19 choose systemd[1]: xremap.service: Scheduled restart job, restart counter is at 5.
6月 23 08:21:19 choose systemd[1]: Stopped xremap aigo 87 keyboard 2023.
6月 23 08:21:19 choose systemd[1]: xremap.service: Start request repeated too quickly.
6月 23 08:21:19 choose systemd[1]: xremap.service: Failed with result 'exit-code'.
6月 23 08:21:19 choose systemd[1]: Failed to start xremap aigo 87 keyboard 2023.
```

So how can I auto run xremap after login?

My OS info is Kubuntu 22.10 with x11.

**Comment by k0kubun** [comment]
Did you look at logs with journalctl? What does it say when it fails?

Also, it's a known problem that `systemctl enable` doesn't necessarily work unless you figure out the proper dependencies in your environment. Some people have discussed the actual dependencies in past issues (that I can't remember), but I just use something else instead https://github.com/k0kubun/xremap/issues/188#issuecomment-1272749372.

**Comment by Thesoul20** [comment]
Yes, I have read the #188 but the setting cannot run well.

Now, I replace the `~/` with the absolute path and change the `xremap.service` file like below:

```shell
# ~/.config/xremap/aligo87.yml 
[Unit]
Description=xremap aigo 87 keyboard 2023 
After=default.target

[Service]
Restart=always
ExecStart=bash /home/choose/.config/xremap/aigo87.sh
ReStartSec=60
StartLimitInterval=30
[Install]
WantedBy=default.target
```
then the xremap work well. Thank you.
