### ISSUE TITLE
Export virtual keyboard capability as a library

### ISSUE THREAD

**Issue by ModProg** [k0kubun/xremap#314]
It would be quite neat to be able to create a virtual input device using the same capabilities as xremap.

**Comment by k0kubun** [comment]
Sorry, I don't understand what you want and the use case of it. Can you describe the desired interface and when you want to use it?

**Comment by ModProg** [comment]
My thought of use case would be writing some automatization software that needs to perform inputs.

I thought maybe we could just add a `lib.rs` and make the corresponding functions public.

**Comment by k0kubun** [comment]
I think you can depend on evdev directly and just follow what xremap does. For any of my projects that are mainly distributed as a single-binary command, I'd like to reserve the right to only maintain its command-line interface and never consider the public functions of the crate as a library that this project needs to maintain. Thank you for your understanding.
