### ISSUE TITLE
Possible regression for rootless under Debian 12

### ISSUE THREAD

**Issue by sebasuh** [k0kubun/xremap#321]
Hi,
thanks for this awesome piece of software :heart: . I just found out about it and installed it right away.
I got it working with sudo in non-application specific mode but am a bit unsure if allowing root access to dbus poses any risks (I am unfamiliar with the details of dbus). So I wanted to get it working in rootless mode application-specific mode. However I get this error every time:
```
Error: Failed to prepare an output device: Permission denied (os error 13)
```
I have installed xremap via cargo and tried the rootless setup for Ubuntu as well as generic. xremap is able to detect input devices and autoselects a few of them but then fails. Specific selection of a `/dev/input/event*` also produces the same error.
udev rule seems to set permissions on `event*` devices correctly but I was wondering if I need write access to `/dev/input/` which is not the case.

System info:
- OS: Debian 12
- DE: Gnome 43.4-1 using Wayland
- cargo & rust: 1.71

Tried to search for known quirks of Debian with writing input devices but came up with nothing helpful. Any ideas?

**Comment by k0kubun** [comment]
> udev rule seems to set permissions on event* devices correctly but I was wondering if I need write access to /dev/input/ which is not the case.

Did you execute the commands under "If you want to run xremap without sudo, click here." in the README?

**Comment by sebasuh** [comment]
Yes, sorry, ,that's what I meant by "tried the rootless setup for Ubuntu as well as generic." I tried
```
sudo gpasswd -a YOUR_USER input
echo 'KERNEL=="uinput", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/input.rules
```
(although I used `usermod` but same result) as well as
```
sudo usermod -aG input YOUR USER
echo 'KERNEL=="event*", NAME="input/%k", MODE="660", GROUP="input"' | sudo tee /etc/udev/rules.d/input.rules
```
The rule gets applied because the permissions on device files in `/dev/input` changed after reboot and my user is part of the `input` group which exists.

**Comment by sebasuh** [comment]
I haven't looked into xremap's code itself since I am really a beginner with Rust but is it trying to create another device in `/dev/input`? If so, the directory itself is not writable for the `input` group. I also `chmod`ed the directory but it did not make a difference. The kernel probably blocks device creation in some other way

**Comment by k0kubun** [comment]
I believe https://github.com/k0kubun/xremap/pull/322 solved your problem. Closing, thanks to your effort.
