### ISSUE TITLE
sudden "Permission denied (os error 13)" even when using udev rule

### ISSUE THREAD

**Issue by U1s2e3r4n5a6m7e** [k0kubun/xremap#329]
Before today, I had been successfully using `xremap` as rootless on my `Arch Linux` system without needing to use `sudo`. However, after rebooting today, I encountered an error message:

```
Error: Failed to prepare an output device: Permission denied (os error 13)
```

I hadn't rebooted my system between:
July 30th at 16:30 UTC,
August 3rd at 05:20 UTC,
so I suspect the issue _must_ have arisen during that time period, maybe with a system update.

As I searched for a solution to the problem, I came across this issue #321. I decided to try the fix suggested there, which involved adding `TAG+="uaccess"` to my udev input.rules file:
```
KERNEL=="uinput", GROUP="input", MODE="0660", TAG+="uaccess"
```
After making this change, `xremap` started **working again**. 
The same process applies to both versions, v0.8.5 and v0.8.6, and I believe it is not related to the xremap version.

Also, I realized that the final version still worked even after I removed the `MODE` parameter:
```
KERNEL=="uinput", GROUP="input", TAG+="uaccess"
```

I am not sure if I am the only one encountering this issue on Arch Linux.
<sup>But, I am creating this issue to assist anyone who comes across a similar problem, as it can be a frustrating experience for those who heavily rely on this program for their daily Linux usage.</sup>

**Comment by kohane27** [comment]
I also have the same issue. Currently just manually using `sudo` to run `xremap`.

**Comment by U1s2e3r4n5a6m7e** [comment]
I'm grateful for your comment, and it's reassuring to hear that I'm not alone in encountering this issue ( '^ ^). Oh, and I almost forgot to mention that for the changes to take effect, a **reboot** of the PC is **required**.

**Comment by U1s2e3r4n5a6m7e** [comment]
> Or, alternatively:
> 
> ```shell
> sudo udevadm control --reload-rules
> sudo udevadm trigger
> ```

Unfortunately, these commands usually suffice under normal conditions, but for the uinput scenario, they don't seem to work, at least for me. Despite working for my bluetooth udev rules, I am disappointed to say that I have to resort to rebooting in order to see the changes take effect.

**Comment by kohane27** [comment]
I just restarted my machine and `xremap` is working without requiring root! Thank you again for raising this issue and providing a solution!

**Comment by k0kubun** [comment]
:+1:

Does this mean that `echo 'KERNEL=="uinput", GROUP="input", MODE="0660"'` in the README stopped working for Arch Linux and we need to change it to `KERNEL=="uinput", GROUP="input", TAG+="uaccess"` (or with MODE)?

**Comment by k0kubun** [comment]
Assuming so, I updated the README accordingly. If anything is still wrong with it, I'd appreciate pull requests.

**Comment by Legisign** [comment]
This seems to be happening again even if I use the current (corrected) udev rule. Tested in both Debian 12 and openSUSE Leap 15.5.

I also tried adding MODE="0660", just in case, but as I expected, no help from there.

**Comment by k0kubun** [comment]
Honestly I don't know what made it fail since we aren't changing anything from xremap's end. It's most likely a bug or a breaking change on the udev side. Is it not an option to just start xremap with sudo for you?

**Comment by Legisign** [comment]
Of course `sudo` can be used, but it means that the program cannot be run automatically on login. (Well, can but it wouldn’t be easy.)

**Comment by Legisign** [comment]
And what on earth… Now it DOES work on openSUSE Leap! I have to check everything, maybe I did something wrong last time.

**Comment by blob42** [comment]
For anyone who still encounters the issue even after trying all the previous
solutions, make sure to explicitly enable the uinput module at boot. I am on
Arch and uinput seems automatically loaded but the udev rules are not applied if
it is not modprobed. On arch adding it to `/etc/modules-load.d/...` solved it for
me. 

See https://github.com/chrippa/ds4drv/issues/93#issuecomment-265300511 for more context.
