### ISSUE TITLE
emacs + disabling gnome console

### ISSUE THREAD

**Issue by xpusostomos** [k0kubun/xremap#344]
So I want to do the obvious .. have emacs keybindings, but obviously not in the console. Because C-d maps to delete, but in shell you want it to be EOF. So... I took the emacs.yml sample code from this web site and I added:

```
    application:
      not: [ emacs.Emacs, Google-chrome, firefox, org.gnome.Console ]
```

So good, it disables it in emacs itself, that's a win.. As far as the name of gnome console, I noticed that xremap prints out the current app on its stdout. However not so with gnome-console. Instead it prints:

Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 2, bad_value: 0, minor_opcode: 0, major_opcode: 20, extension_name: None, request_name: Some("GetProperty") }

An X11 error seems odd, since this is Wayland.

The suggested command doesn't work:
```
busctl --user call org.gnome.Shell /com/k0kubun/Xremap com.k0kubun.Xremap WMClasses
Failed to set bus address: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
```

I tried various combinations of --machine=<user>@.host to no avail

So I tried the looking glass lg thing, and it seemed to say the name was org.gnome.Console. However that doesn't seem to work because if I press C-d, instead of exiting the shell as you'd expect, it beeps, presumably because its mapped it to Delete.

So the question is, how to disable the script for gnome console?

**Comment by chrisbitmead** [comment]
Further information, adding "xkd" to the list of applications works if I'm running X11. But when I switch back to Wayland that doesn't work. So I don't know if Wayland and X11 are supposed to be consistent in their app names or not, or whether there's a different app name under wayland yet for me to discover, or whether this is just a bug for Wayland and I'm going to have to stick to X11.

**Comment by k0kubun** [comment]
> An X11 error seems odd, since this is Wayland.

I just want to double-check: You're using the xremap binary for gnome instead of the x11 one, is that correct?

Do you see an XWayland process if you list processes? I've never seen it myself, but that might explain the situation.

> So I tried the looking glass lg thing, and it seemed to say the name was org.gnome.Console. However that doesn't seem to work because if I press C-d, instead of exiting the shell as you'd expect, it beeps, presumably because its mapped it to Delete.

Could you start xremap with `RUST_LOG=debug xremap`, reproduce the problem, and share the entire output of the command here? That would explain what xremap is doing and why it's doing it.

> So I don't know if Wayland and X11 are supposed to be consistent in their app names or not

They aren't consistent. At least the names of some applications I use aren't.

> whether this is just a bug for Wayland and I'm going to have to stick to X11.

A lot of features are lacking in the Wayland protocol. You might feel it's a bug, but it could be by design for them. As a person who has ported X11 tools to Wayland, I wouldn't recommend using Wayland unless you want to use something that exists only in Wayland, e.g. Hyprland. Given that it's lacking so many things after years of development, it would take tens of years for Wayland to reach X11 parity if it ever did. If you're a GNOME user like me, which works on both platforms, I don't get the motivation to use the Wayland version of it.

**Comment by chrisbitmead** [comment]
@k0kubun I'm using this one from Arch Linux: https://aur.archlinux.org/packages/xremap-x11-bin  ... 

Yes I see a wayland process if I select Gnome-Wayland as I login. Of course if I select Gnome X11, I don't.

I  think I'll switch to KDE for a while, i've come back to Linux from a long hiatus, and I'm not that impressed with gnome. KDE apparently only runs on X11.

Below is rust debug when logged in as wayland. I'm pressing C-d in console which is presumably being mapped to delete when it should be EOF. It kinda looks to me it can't identify what wayland window its in, but starts doing X11 things.

```
application-client: X11 (supported: true)
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 2, bad_value: 0, minor_opcode: 0, major_opcode: 20, extension_name: None, request_name: Some("GetProperty") }
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 2, bad_value: 0, minor_opcode: 0, major_opcode: 15, extension_name: None, request_name: Some("QueryTree") }
[2023-09-21T09:29:14Z DEBUG xremap::action_dispatcher] 0: KEY_LEFTCTRL
[2023-09-21T09:29:14Z DEBUG xremap::action_dispatcher] 1: KEY_DELETE
[2023-09-21T09:29:14Z DEBUG xremap::action_dispatcher] 0: KEY_DELETE
[2023-09-21T09:29:14Z DEBUG xremap::action_dispatcher] 1: KEY_LEFTCTRL
[2023-09-21T09:29:14Z DEBUG xremap::event_handler] => 0: KEY_D
[2023-09-21T09:29:14Z DEBUG xremap::action_dispatcher] 0: KEY_D
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 3, bad_value: 0, minor_opcode: 0, major_opcode: 20, extension_name: None, request_name: Some("GetProperty") }
[2023-09-21T09:29:15Z DEBUG xremap::event_handler] => 1: KEY_D
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 2, bad_value: 0, minor_opcode: 0, major_opcode: 15, extension_name: None, request_name: Some("QueryTree") }
[2023-09-21T09:29:15Z DEBUG xremap::action_dispatcher] 0: KEY_LEFTCTRL
[2023-09-21T09:29:15Z DEBUG xremap::action_dispatcher] 1: KEY_DELETE
[2023-09-21T09:29:15Z DEBUG xremap::action_dispatcher] 0: KEY_DELETE
[2023-09-21T09:29:15Z DEBUG xremap::action_dispatcher] 1: KEY_LEFTCTRL
[2023-09-21T09:29:15Z DEBUG xremap::event_handler] => 0: KEY_D
[2023-09-21T09:29:15Z DEBUG xremap::action_dispatcher] 0: KEY_D
[2023-09-21T09:29:16Z DEBUG xremap::event_handler] => 1: KEY_D
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 3, bad_value: 0, minor_opcode: 0, major_opcode: 20, extension_name: None, request_name: Some("GetProperty") }
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 0: KEY_LEFTCTRL
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 1: KEY_DELETE
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 0: KEY_DELETE
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 1: KEY_LEFTCTRL
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 2, bad_value: 0, minor_opcode: 0, major_opcode: 15, extension_name: None, request_name: Some("QueryTree") }
[2023-09-21T09:29:16Z DEBUG xremap::event_handler] => 0: KEY_D
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 0: KEY_D
[2023-09-21T09:29:16Z DEBUG xremap::event_handler] => 1: KEY_D
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 3, bad_value: 0, minor_opcode: 0, major_opcode: 20, extension_name: None, request_name: Some("GetProperty") }
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 2, bad_value: 0, minor_opcode: 0, major_opcode: 15, extension_name: None, request_name: Some("QueryTree") }
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 0: KEY_LEFTCTRL
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 1: KEY_DELETE
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 0: KEY_DELETE
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 1: KEY_LEFTCTRL
[2023-09-21T09:29:16Z DEBUG xremap::event_handler] => 0: KEY_D
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 0: KEY_D
[2023-09-21T09:29:16Z DEBUG xremap::event_handler] => 1: KEY_D
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 3, bad_value: 0, minor_opcode: 0, major_opcode: 20, extension_name: None, request_name: Some("GetProperty") }
Reconnecting to X11 due to error: X11 error X11Error { error_kind: Window, error_code: 3, sequence: 2, bad_value: 0, minor_opcode: 0, major_opcode: 15, extension_name: None, request_name: Some("QueryTree") }
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 0: KEY_LEFTCTRL
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 1: KEY_DELETE
[2023-09-21T09:29:16Z DEBUG xremap::action_dispatcher] 0: KEY_DELETE
```

**Comment by k0kubun** [comment]
I wonder if @xpusostomos also uses Arch Linux and xremap-x11-bin, but it's not supposed to be used on GNOME Wayland. I'll work on xremap-gnome-bin shortly.

**Comment by k0kubun** [comment]
Oh, it already exists. That's interesting. Can you two try using `xremap-gnome-bin` instead?

**Comment by k0kubun** [comment]
@szdytom Could you add me as a maintainer to https://aur.archlinux.org/packages/xremap-gnome-bin? We're automating the process for x11 and hypr at https://github.com/xremap/aur-autoupdater, and we can include gnome there.

**Comment by szdytom** [comment]
@k0kubun Cool! I've added already :)

**Comment by k0kubun** [comment]
Thanks! I ported your PKGBUILD to the repository at https://github.com/xremap/aur-autoupdater/pull/29.

**Comment by xpusostomos** [comment]
@k0kubun So... for my understanding, why is there an xremap AND and xremap-gnome? As I said, xremap mostly worked in Gnome, it was just identifying gnome console that was a problem. BTW, is the xremap for gnome, or is it really for wayland?

**Comment by k0kubun** [comment]
The thing you're calling xremap is xremap-x11. xremap-x11 works for X11, and xremap-gnome works for gnome. xremap-x11 works perfectly on X11 Gnome, and partially works on Wayland Gnome for things that are actually run as x11 under XWayland. xremap-gnome works fine for both X11 Gnome and Wayland Gnome.

There's no Wayland protocol that supports the feature xremap provides, which is why this is so messed up. If you choose x11, xremap-x11 works no matter what WM you choose. If you choose Wayland, nothing works across all WMs because the protocol doesn't support it. Therefore, if you decide to be a Wayland user, you have to pick a WM-specific implementation, such as xremap-gnome.

It seems like you're using xremap-x11 on Gnome Wayland. xremap-gnome exists solely for Gnome Wayland, so please use that instead.

**Comment by k0kubun** [comment]
Oh, I forgot to share that I actually intend to combine all binaries at some point though. But as of now, one binary per protocol.
