### ISSUE TITLE
How to know the 'FN' button name?

### ISSUE THREAD

**Issue by kmvan** [k0kubun/xremap#35]

**Comment by k0kubun** [comment]
It seems to be a keyboard-level or BIOS-level feature https://stackoverflow.com/questions/23495426/is-fn-key-not-defined-in-x-window-in-x11-keysymdef-h, so I don't think we can control it from software. Sorry.

**Comment by Shatur** [comment]
@k0kubun looks like this program supports it: https://github.com/samvel1024/kbct

**Comment by k0kubun** [comment]
They say "Much **like** fn key", which implies it's not an actual fn key. That is already possible with xremap too.

**Comment by Shatur** [comment]
Got it, thanks!

**Comment by Shatur** [comment]
Wait, no, I mean that I can use `fn` as modifier and it works. But my keyboard [is special](https://pine64eu.com/product/pinephone-pinephone-pro-keyboard-case/), maybe this is why it works.

**Comment by k0kubun** [comment]
You can try `RUST_LOG=debug xremap` and see what events it prints. If you tap the fn key alone and it prints something, you should be able to remap that based on the event name shown in the debug log.

**Comment by Shatur** [comment]
Thank you!
