### ISSUE TITLE
Several keybinding not work on GNOME 45 + Wayland when use with wayland version binary.

### ISSUE THREAD

**Issue by zw963** [k0kubun/xremap#368]
I use the examples/emacs.conf, some keys works, e.g. Alt+f, Alt + b, but, C-f, C-b not work, e.g. when use with chrome, C-f always active the `find` feature in the browser.

Thanks.

**Comment by k0kubun** [comment]
* May I double-check that you're using `example/emacs.yml` as is; no `application` filter?
* Can you run `RUST_LOG=debug xremap`, press C-f with and without Chrome, and report the entire output of the xremap command here?

**Comment by zw963** [comment]
Oops, after debug, i know the issue come from.

I use following xkb config for mapping my Capslock -> L-Ctrl and R-Alt -> Capslock.

```
# /usr/share/X11/xkb/symbols/new_ctrl

partial modifier_keys
xkb_symbols "new_ctrl" {
    replace key <RALT> { [ Caps_Lock, Caps_Lock ] };
    modifier_map Lock { <RALT> };
    replace key <CAPS> { [ Control_L, Control_L ] };
    modifier_map Control { <CAPS>, <LCTRL> };
    };
```

It works well for GNOME + Wayland, but, when use with xremap, it recognized Capslock as it was before mapping, so, All Ctrl-?? key binding not work.

It works after add following config into emacs.yml

```
modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      Alt_R: Capslock
```
