### ISSUE TITLE
xremap hangs when I run it

### ISSUE THREAD

**Issue by seancolsen** [k0kubun/xremap#372]
I want to use xremap but I'm having some trouble running it. If anyone can help me troubleshoot this, I'd really appreciate it!

## System info

- KDE Neon running with Wayland

- `lsb_release -a`

    > ```
    > No LSB modules are available.
    > Distributor ID: Neon
    > Description:    KDE neon 5.27
    > Release:        22.04
    > Codename:       jammy
    > ```

- `uname -r`

    > ```
    > 6.2.0-36-generic
    > ```

- `xremap --version`

    > ```
    > xremap 0.8.11
    > ```

## What I've done so far

1. Installed xremap via: 

    ```
    cargo install xremap --features kde
    ```

1. Added my user to the `input` group

    ```
    sudo gpasswd -a sean input
    ```

1. Added udev rules

    ```
    echo 'KERNEL=="uinput", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/input.rules
    ```

1. Restarted my machine.

1. Generated a trivial `xremap.config.yml` file containing:

    ```yml
    keymap:
    - name: Test
        remap:
        SUPER_L-KEY_MINUS: [KEY_MINUS, KEY_MINUS, KEY_MINUS]
    ```

1. Try to run xremap (without sudo)

    `xremap xremap.config.yml`

    > ```
    > Selecting devices from the following list:
    > ------------------------------------------------------------------------------
    > /dev/input/event0 : Sleep Button
    > /dev/input/event1 : Lid Switch
    > /dev/input/event10: ThinkPad Extra Buttons
    > /dev/input/event11: foostan Corne Keyboard (crkbd)
    > /dev/input/event12: foostan Corne Keyboard (crkbd) Mouse
    > /dev/input/event13: foostan Corne Keyboard (crkbd) System Control
    > /dev/input/event14: foostan Corne Keyboard (crkbd) Consumer Control
    > /dev/input/event15: HDA Intel PCH Mic
    > /dev/input/event16: HDA Intel PCH Headphone
    > /dev/input/event17: HDA Intel PCH HDMI/DP,pcm=3
    > /dev/input/event18: HDA Intel PCH HDMI/DP,pcm=7
    > /dev/input/event19: HDA Intel PCH HDMI/DP,pcm=8
    > /dev/input/event2 : Power Button
    > /dev/input/event20: HD Pro Webcam C920
    > /dev/input/event21: Integrated Camera: Integrated C
    > /dev/input/event3 : AT Translated Set 2 keyboard
    > /dev/input/event4 : SynPS/2 Synaptics TouchPad
    > /dev/input/event5 : TPPS/2 IBM TrackPoint
    > /dev/input/event6 : Video Bus
    > /dev/input/event7 : Logitech MX Anywhere 3
    > /dev/input/event8 : Wacom Pen and multitouch sensor Finger
    > /dev/input/event9 : Wacom Pen and multitouch sensor Pen
    > ------------------------------------------------------------------------------
    > Selected keyboards automatically since --device options weren't specified:
    > ------------------------------------------------------------------------------
    > /dev/input/event11: foostan Corne Keyboard (crkbd)
    > /dev/input/event3 : AT Translated Set 2 keyboard
    > ------------------------------------------------------------------------------
    > ```

    **The command just hangs here without exiting.**
    
1. I need to kill it with <kbd>Ctrl</kbd>+<kbd>C</kbd>.

1. After this, my remap does not appear to work.

## Troubleshooting

Here's what various commands yield on my machine:

- `groups`

    > ```
    > sean adm cdrom sudo dip plugdev input lpadmin sambashare
    > ```

- `cat /etc/udev/rules.d/input.rules`

    > ```
    > KERNEL=="uinput", GROUP="input", TAG+="uaccess"
    > ```

- `modprobe uinput`

    > _(no output)_

- `lsmod | grep uinput`

    > _(no output)_

    > **Note**
    >
    > This seems to be where I'm stuck. No matter what I do, I can't seem to get `lsmod` to ever show `uinput`.

- `find /lib/modules/$(uname -r) -name uinput.ko`

    > _(no output)_

- `grep uinput /lib/modules/$(uname -r)/modules.builtin`

    > ```
    > kernel/drivers/input/misc/uinput.ko
    > ```

- `modinfo uinput`

    > ```
    > name:           uinput
    > filename:       (builtin)
    > license:        GPL
    > file:           drivers/input/misc/uinput
    > description:    User level driver support for input subsystem
    > author:         Aristeu Sergio Rozanski Filho
    > alias:          devname:uinput
    > alias:          char-major-10-223
    > ```

## I've also tried

- Adding `input` to `/etc/modules-load.d/uinput.conf` and restarting.

    (`lsmod | grep uinput` still shows as empty afterwards.)

- Running with root

    `sudo /home/sean/.cargo/bin/xremap xremap.config.yml`

    Here I get the same behavior as when I run with my user (xremap prints some output and then hangs)

**Comment by k0kubun** [comment]
This report is very well written, thanks.

Could you also see what happens if you build xremap without `--features kde`? (i.e. just `cargo install xremap`)

**Comment by seancolsen** [comment]
Thanks for the help, @k0kubun.

After reinstalling xremap via `cargo install --force xremap`, I'm still observing the same behavior where xremap hangs when I run it either without sudo or with sudo:

- `xremap xremap.config.yml`
- `sudo /home/sean/.cargo/bin/xremap xremap.config.yml`

**Comment by k0kubun** [comment]
OK, so it's probably not about the communication with KDE for `application` filter but about evdev or uinput. 

I wonder where it's stuck. Could you somehow attach gdp to the xremap process once it gets stuck and let it print the backtrace? I don't have an environment that reproduces the issue locally, so I need your environment to reproduce it and help us investigate it.

**Comment by hectorhuertas** [comment]
I came to this issue with the same problem, but managed to solve it.

My mistake was that `xremap` needs to run as a daemon, so it needs to be running for the remaps to work. So when running it in a terminal, it "hangs" because it's supposed to be left running. But it is working, so the remaps are active and working.

@seancolsen maybe you have the same misunderstanding as me and it is actually working, but you are killing it (`Ctrl`+`C`) before trying the remaps?

k0kubun thanks a lot for your great work. I know having detailed instructions about running `xremap` as a daemon can get quite wild, but being a bit more explicit about the binary being intended to run as a daemon would have helped me avoid the mistake.

Hope that helps

**Comment by seancolsen** [comment]
@hectorhuertas BRILLIANT! THANK YOU!

> xremap needs to run as a daemon

Ok this makes sense now. But after reading the entire docs page I definitely had no idea that's how it's supposed to work. 🤣

I've opened #377 to address this via documentation improvement.

**Comment by k0kubun** [comment]
Ohhh, I see. That was kind of hard for me to figure out at this point, but I'm glad two of you managed to figure it out. Thank you for the PR too!
