### ISSUE TITLE
[GNOME Wayland, NixOS] Can't get application specific keymappings to work

### ISSUE THREAD

**Issue by SayantanRC** [k0kubun/xremap#378]
Here is the configuration I am trying to make work:
```
- name: Nautilus
  remap:
    Backspace: LeftAlt-Left
  application:
    only: org.gnome.Nautilus
```

But it does not work.  

Here is the full configuration (nix flake):

```
{ config, lib, pkgs, inputs, username, ... }:
{

  imports = [
    inputs.xremap-flake.nixosModules.default
  ];
  
  services.xremap = {
    userName = "${username}";
    withGnome = true;
    yamlConfig = ''
    keymap:
      - name: Home-End keys
        remap:
          RightAlt-Right: End
          RightAlt-Left: Home
          RightAlt-Up: PageUp
          RightAlt-Down: PageDown
          RightAlt-RightBrace: End
          RightAlt-LeftBrace: Home
          
      - name: Screenshots
        remap:
          Shift-Win-S:
            remap:
              Shift-Win-S: Print
              S: Print
              P: Shift-Print
              
      - name: Nautilus
        remap:
          Backspace: LeftAlt-Left
        application:
          only: org.gnome.Nautilus
    '';
  };
}
```

All the other keybindings work, except the Nautilus specific one.

To make matters worse, if the Nautilus specific keybinding is present and I reboot the system, all keybindings stop working.

Any help is appreciated.

Edit: [Xremap GNOME extension](https://extensions.gnome.org/extension/5060/xremap/) is installed and turned on.

**Comment by k0kubun** [comment]
Could you start xremap with `RUST_LOG=debug xremap ...`, switch to Nautilus, press Backspace, and share the entire output of the xremap command?

Also, what's the GNOME version and the extension version you installed?

**Comment by SayantanRC** [comment]
```
[sayantan@nixos:~]$ RUST_LOG=debug xremap ...
xremap: command not found
```

Maybe because it is Nix OS?

```
[sayantan@nixos:~]$ type xrepmap
bash: type: xrepmap: not found
```

**Comment by k0kubun** [comment]
NixOS indeed has a unique directory structure. I need you to discover the path. One simple way might be to run `sudo find / | grep "/xremap$"`. You'd also need to stop currently-running xremap before running another one.

**Comment by VTimofeenko** [comment]
Try setting `services.xremap.serviceMode = "user"` as withGnome does not work with system-wide service.

I also added a `services.xremap.debug` option to enable debug logging through the systemd service, and you can get the logs through `journalctl -u xremap.service` or `journalctl --user -u xremap.service` if using a user service.

I will implement a warning for withGnome && systemMode == "system" in xremap/nix-flake/issues/48

**Comment by SayantanRC** [comment]
@VTimofeenko @k0kubun  using serviceMode = "user" does get it to start working. Thank you so much.
