### ISSUE TITLE
make failure on ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by MikihikoNakao** [k0kubun/xremap#38]
I'm very novice to ruby, so I may be saying something very stupid, but `make` failed because of `mgem not found: mruby-io`.
I could compile after adding a line `conf.gem :github => 'iij/mruby-io'` in build_config.rb and the program works excellently!
I'm leaving this message because it is not so obvious for a non-ruby user like me.

I like this program very much, thank you. :smile:

**Comment by k0kubun** [comment]
Thank you for reporting it. It's known that the relationship between mruby and mruby-io changed after I developed xremap, however, it's interesting that it happens while we fix the mruby revision. Anyway, I'm thinking about fixing the build system in near future, so hopefully this issue will be gone at that point.

**Comment by k0kubun** [comment]
So I rewrote this project in Rust and now we even have a binary distribution, which you don't need to build yourself. So this problem should be gone.
