### ISSUE TITLE
No device selected 

### ISSUE THREAD

**Issue by Zithin10k** [k0kubun/xremap#388]
I am using kubuatu
When I run 
xremap config.yml
Out put error:
Selecting devices from the following list:
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
Error: Failed to prepare input devices: No device was selected!

If. I run 
xremap --device /dev/input/event2 config.yml 
out put error again
Selecting devices from the following list:
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Selected devices matching ["/dev/input/event2"]:
------------------------------------------------------------------------------
Error: Failed to prepare input devices: No device was selected!
pls help..

**Comment by k0kubun** [comment]
Can you please show the entire output of the command? You quoted only part of it, and it's missing the important parts. Just share the entire output please, from the beginning, including the command name, to the end where you interrupted the process.

**Comment by snowyru** [comment]
I am getting the same Issue. It seems to be working with an external usb keyboard but not my laptops built in keyboard.
here is the command and its output

xremap ~/.config/xremap/config.yml

Selecting devices from the following list:
------------------------------------------------------------------------------
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
Error: Failed to prepare input devices: No device was selected!

Using Kde wayland x86_64 on arch

**Comment by k0kubun** [comment]
What does your `ls -la /dev/input` look like?

**Comment by zvolin** [comment]
Hey, just came around this.
I'm trying to configure macbook m2 air with asahi x fedora remix and I wanted to remap some modifiers (like switch win_r with alt_r).
I have the same issue.
```bash
❯ ls -la /dev/input 
drwxr-xr-x@     - root 28 Jan 00:12 by-path
crw-rw----@ 13,64 root 28 Jan 00:12 event0
crw-rw----@ 13,65 root 28 Jan 00:12 event1
crw-rw----@ 13,66 root 28 Jan 00:12 event2
crw-rw----@ 13,67 root 28 Jan 00:12 event3
crw-rw----@ 13,68 root 28 Jan 00:12 event4
crw-rw----@ 13,69 root 28 Jan 00:12 event5
crw-rw----@ 13,63 root 28 Jan 00:12 mice
crw-rw----@ 13,32 root 28 Jan 00:12 mouse0
crw-rw----@ 13,33 root 28 Jan 00:12 mouse1
```

**Comment by k0kubun** [comment]
And what's your `xremap`'s output when it starts? Does your kernel have uinput, have you configured udev, and do you use sudo to start xremap?

**Comment by zvolin** [comment]
My xremap config:
```yml
modmap:
  - name: Alt-gr
    remap:
      super_ gr: alt_r
      alt_r: super_r
```

So I wasn't running with sudo. I had the following in my `hyprland.conf` which I thought runs with expected privelages
```
exec-once = xremap ~/.config/xremap/config.yml
```
this doesn't seem to take any effect tho.

The `No device selected' shows up without a sudo. With sudo I get the following
```
Selecting devices from the following list:
------------------------------------------------------------------------------
/dev/input/event0 : Apple MTP multi-touch
/dev/input/event1 : Apple MTP keyboard
/dev/input/event2 : Mac14,7 Touch Bar
/dev/input/event3 : Apple SMC power/lid events
/dev/input/event4 : MacBook Pro J493 Headphone Jack
/dev/input/event5 : Dynamic Function Row Virtual Input Device
------------------------------------------------------------------------------
Selected keyboards automatically since --device options weren't specified:
------------------------------------------------------------------------------
/dev/input/event1 : Apple MTP keyboard
------------------------------------------------------------------------------
```
and then it starts appending empty lines to the stdout indefinitely. Also my touchpad stops working after this command.

I have added the input group rule to udev. The uinput module seems to be there:
```bash
❯ lsmod | grep uinput
uinput                 49152  1
```

**Comment by zvolin** [comment]
I think it's unrelated to this issue then

**Comment by zvolin** [comment]
this is related stderr from launching from hyprland
```
       │ File: /proc/21219/fd/2
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ Error: Failed to load config '/home/zwolin/.config/xremap/config.yml': could not find expected ':' at line 8 column 1, while scanning a simple key at line 7 column 1
   2   │ 2024-01-28 12:46:26 - [main.c:293] Found config * for output eDP-1 ((null) (null))
   3   │ 
   4   │ (waybar:21018): Gtk-WARNING **: 12:46:26.175: Theme parsing error: style.css:95:18: Not using units is deprecated. Assuming 'px'.
   5   │ 
   6   │ (waybar:21018): Gtk-CRITICAL **: 12:46:26.333: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
   7   │ 
   8   │ (waybar:21018): Gtk-CRITICAL **: 12:46:26.333: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
   9   │ 
  10   │ (waybar:21018): Gtk-CRITICAL **: 12:46:26.333: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
  11   │ 
  12   │ (waybar:21018): Gtk-CRITICAL **: 12:46:26.333: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
  13   │ 
  14   │ (waybar:21018): Gtk-CRITICAL **: 12:46:26.333: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
  15   │ 
  16   │ (waybar:21018): Gtk-CRITICAL **: 12:46:26.333: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
  17   │ Gdk-Message: 12:46:29.813: Error flushing display: Resource temporarily unavailable
  18   │ [Parent 21219, Main Thread] WARNING: Failed to call GetIdletime(): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
  19   │ : 'glib warning', file /builddir/build/BUILD/firefox-120.0.1/toolkit/xre/nsSigHandlers.cpp:187
  20   │ 
  21   │ ** (firefox:21219): WARNING **: 12:46:38.168: Failed to call GetIdletime(): GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

**Comment by zvolin** [comment]
I don't know why are there waybar and firefox messages :d

**Comment by k0kubun** [comment]
> then it starts appending empty lines to the stdout indefinitely

It's not related to sudo. It's just a general problem in Wayland. When you start xremap with sudo but without pressing an Enter, e.g. through hyprland.conf, it should not happen. There's an idea to deal with the situation from xremap's end, but it has not been implemented yet.

Until the fix is introduced or you figure out how to configure permission, I suggest you to use sudo to start xremap.

**Comment by zvolin** [comment]
thanks, was able to get it running after using sudo in hyprland.conf + the NOPASSWD for xremap in /etc/sudoers

**Comment by al23212321** [comment]
> thanks, was able to get it running after using sudo in hyprland.conf + the NOPASSWD for xremap in /etc/sudoers

Hi, whats the entry you used in /etc/sudoers?
is it like this?
`myusernam ALL=(root) NOPASSWD: /usr/bin/xremap`

**Comment by zvolin** [comment]
```
ALL ALL=NOPASSWD:/home/zwolin/.cargo/bin/xremap
```
not the best one but works :sweat_smile:
