### ISSUE TITLE
Unhelpful Serde error on config structure the docs seem to say should work

### ISSUE THREAD

**Issue by ssokolow** [k0kubun/xremap#406]
After a distro update introduced a persistent refusal to keep xbindkeys bound to one of the buttons on my ATi Remote Wonder II, I decided to write something that could just bypass X11 altogether and go straight to evdev but, before I made the effort, I found xremap in the lib.rs output while I was searching for evdev bindings.

Unfortunately, for this key...

```
Event: time 1705967070.119360, type 1 (EV_KEY), code 214 (KEY_QUESTION), value 1
```

...I'm getting this error message...

```
Error: Failed to load config 'xremap.yml': modmap[0].remap: data did not match any variant of untagged enum ModmapAction at line 4 column 7
```

...from this config file, and I can't figure out why:

```
modmap:
  - name: Talking Clock
    remap:
      KEY_QUESTION:
        launch: ["sh", "-c", "~/bin/saytime"]
```

As someone who's used untagged enums before with Serde and had to deal with the terrible error messages, I feel your pain on this one, but I think there needs to be *something* fixed... whether it's better docs to keep people like me from getting into this situation, better evdev support if the error is actually "I have no idea what `KEY_QUESTION` is", or some kind of better error message... possibly by having it list out the error message each variant of the enum would have given if the enum were tagged and that was what the tag specified.

**Comment by k0kubun** [comment]
Sounds fair. Would you mind filing a pull request for it? I don't know how to properly format error messages in Serde, or if it's even possible to output a message like that.

**Comment by ssokolow** [comment]
The "fix Serde's error message" solution is still on my TODO list for my own project, so I haven't looked into how to solve it that way yet. I more raised it as a hypothetical in case you already knew more about Serde than I did.

That said, do you have any idea what's going wrong here? I need this as part of tooling for managing my sleep issues and, if I don't have a fix within the next hour or two, I'm probably going to have to resort to code-sprinting a "temporary solution that'll probably become permanent" by reviving and adapting something I wrote a decade ago using Python evdev bindings.

**Comment by k0kubun** [comment]
Which problem? The evdev not recognizing `KEY_QUESTION`? Then I recommend you to run `RUST_LOG=debug xremap ...` to see the key code that is recognized by evdev (and xremap).

**Comment by ssokolow** [comment]
Looks like it should work, so I guess that's not the problem.

```
ssokolow@monolith-tng ~ % RUST_LOG=debug xremap empty.yml --device 'ATI Remote Wonder II'
Selecting devices from the following list:
------------------------------------------------------------------------------
/dev/input/event11: ATI Remote Wonder II
/dev/input/event3 : ASRock LED Controller
------------------------------------------------------------------------------
Selected devices matching ["ATI Remote Wonder II"]:
------------------------------------------------------------------------------
/dev/input/event11: ATI Remote Wonder II
------------------------------------------------------------------------------
[2024-01-23T05:05:07Z DEBUG xremap::event_handler] => 1: KEY_QUESTION
[2024-01-23T05:05:07Z DEBUG xremap::action_dispatcher] 1: KEY_QUESTION
[2024-01-23T05:05:08Z DEBUG xremap::event_handler] => 0: KEY_QUESTION
[2024-01-23T05:05:08Z DEBUG xremap::action_dispatcher] 0: KEY_QUESTION
```

(Also, it just ignores `--device /dev/input/ati_remote_wonder_ii` as if I didn't specify it, with that path being via a `SYMLINK+="input/ati_remote_wonder_ii"` in a udev rule.)

**Comment by k0kubun** [comment]
Oh, ok now I get that. `launch` command exists for `modmap` only because somebody wanted to emit different launch commands on press and release (put `launch` under `press` and `release` as the README says). For a single key press to launch a command, you'd like to use `keymap` instead.

```yml
keymap:
  - name: Talking Clock
    remap:
      KEY_QUESTION:
        launch: ["sh", "-c", "~/bin/saytime"]
```

---

I don't know about the symlink problem. I never attempted to create a symlink under `/dev/input`. Matching with "ATI Remote Wonder II" seems fine to me though.

**Comment by ssokolow** [comment]
That's counter-intuitive. The examples in the README give the sense that they should be operating off the same sub-schema.

**Comment by k0kubun** [comment]
I'm thinking of eventually unifying `modmap` and `keymap` and making them just a first layer and a second layer. At that point, the problem would be fixed.

For now, please feel free to file a pull request if you have an idea as to what README would have been easier to understand.

**Comment by ssokolow** [comment]
I'll try to make some time to think about it within the next couple of days. I anticipate having some trouble since I don't like suggesting special-case "*WARNING: Don't do this"-style changes, but I don't have a solid enough understanding of the underlying design to easily make a more broad suggestion.

The most obvious improvement *would* be the error message fix but, as [this blog post](https://www.gustavwengel.dk/serde-untagged-enum-errors-are-bad) and [this closed serde PR](https://github.com/serde-rs/serde/pull/2376) mention, any solution is going to involve reinventing stuff Serde normally generates for you and I'm really not a fan of that sort of thing if I can avoid it... if for no other reason than maintainability.
