### ISSUE TITLE
keymap[0].remap: unknown key '<<' error on  xremap-linux-x86_64-gnome.zip 0.8.14

### ISSUE THREAD

**Issue by zw963** [k0kubun/xremap#409]
I download binary from https://github.com/k0kubun/xremap/releases/download/v0.8.14/xremap-linux-x86_64-gnome.zip

Following is my sample config:

```yml
shared:
  set_mark_remaps: &set_mark_remaps
    # Mark
    C-2: { set_mark: true }
    # Cancel
    C-g: [esc, { set_mark: false }]

keymap:
  - name: Common but not Emacs, konsole, org.gnome.Nautilus
    application:
     not:  [Emacs,emacs,konsole,org.gnome.Nautilus]
    remap:
      <<: *set_mark_remaps
```

I get following error when run `xremap this.yml`

Error: Failed to load config 'emacs3.yml': keymap[0].remap: unknown key '<<' at line 13 column 7

-----------------

But, this is a valid yaml when i load it use ruby `YAML.load_file`.

```sh
 ╰─ $ pry
[1] pry(main)> require 'yaml'
=> true
[2] pry(main)> YAML.load_file('emacs3.yml', aliases: true)
=> {"shared"=>{"set_mark_remaps"=>{"C-2"=>{"set_mark"=>true}, "C-g"=>["esc", {"set_mark"=>false}]}},
 "keymap"=>
  [{"name"=>"Common but not Emacs, konsole, org.gnome.Nautilus",
    "application"=>{"not"=>["Emacs", "emacs", "konsole", "org.gnome.Nautilus"]},
    "remap"=>{"C-2"=>{"set_mark"=>true}, "C-g"=>["esc", {"set_mark"=>false}]}}]}
[3] pry(main)> 
```

Thanks.

**Comment by k0kubun** [comment]
It's not libyaml like ruby but [serde-yaml](https://github.com/dtolnay/serde-yaml), so it's not guaranteed to work like Ruby. If you find an unsupported YAML syntax, please report to serde-yaml instead.

For your example, if you change it to `remap: *set_mark_remaps`, serde-yaml parses it correctly.

**Comment by zw963** [comment]
Thanks, i saw the example in README.md get fixed. :smile:

**Comment by zw963** [comment]
Hi, I saw https://github.com/dtolnay/serde-yaml get archived since Mar 25, 2024, any update on this dependencies?

I expected to use `<<:` hack to simplify my config, so, concerning the changes in this area, thanks!

**Comment by k0kubun** [comment]
No update from my end. I'm open to merging a PR that fixes it.
