### ISSUE TITLE
Can't find keyname for "lessThan/greaterThan" or "ls/gt" on QWERTZ layout keyboard

### ISSUE THREAD

**Issue by theCollectiv** [k0kubun/xremap#415]
I studied [evdev/src/scancodes.rs · emberian/evdev](https://github.com/emberian/evdev/blob/1d020f11b283b0648427a2844b6b980f1a268221/src/scancodes.rs#L26-L572) a pretty good time, but I can't find a key-name for this physical key: "lessThan/greaterThan" or "ls/gt"-key on QWERTZ layout keyboard (key right from the 'Shift-Left key' -> B00 in the picture)
https://en.wikipedia.org/wiki/Keyboard_layout#/media/File:German_keyboard_layout_T2_according_to_DIN_2137-01--2012-06.png

Is there a key-name in xremap/evdev for it available?

**Comment by k0kubun** [comment]
Can you run `RUST_LOG=debug xremap` and press the key you want to remap?

**Comment by theCollectiv** [comment]
```bash
[2024-02-08T22:42:03Z DEBUG xremap::event_handler] => 1: KEY_102ND
[2024-02-08T22:42:03Z DEBUG xremap::action_dispatcher] 1: KEY_102ND
<[2024-02-08T22:42:03Z DEBUG xremap::event_handler] => 0: KEY_102ND
[2024-02-08T22:42:03Z DEBUG xremap::action_dispatcher] 0: KEY_102ND
```

So it may look like KEY_102ND is that key.

Yes! Tested: I can remap it. Thx!

**Comment by theCollectiv** [comment]
Maybe `RUST_LOG=debug xremap` would be very useful in the readme.md.
It makes it very easy to get the names for specific physical keys.
