### ISSUE TITLE
Can't get Print Key Remapping working

### ISSUE THREAD

**Issue by r0uv3n** [k0kubun/xremap#416]
I'm trying to remap the Print Screen Key. I could only find `KEY_PRINT` (with the comment "AC Print") in the scancode list, but a simple
```
modmap:
  name:
    KEY_PRINT: KEY_DOWN
```
does not work on my system (I'm using the NixOS flake). Remapping works fine for other keys.

Am I using the wrong scancode or is there another issue?

**Comment by k0kubun** [comment]
Can you run `RUST_LOG=debug xremap`, press the key, and see what key code it outputs?

**Comment by r0uv3n** [comment]
Ah it gives KEY_SYSRQ, and with that everything works, thank you!
