### ISSUE TITLE
Include mouse buttons

### ISSUE THREAD

**Issue by N4tus** [k0kubun/xremap#44]
Is it possible to allow mouse-buttons to use in a remap? For example map mouse-button 4 to ctrl.

**Comment by k0kubun** [comment]
Yes, it should be. By default, xremap doesn't try to capture the input of a mouse, but if you explicitly select both a mouse and a keyboard by `--device`, mouse buttons like `BTN_LEFT` should be usable in the config. I'll test it and provide an example tonight.

**Comment by k0kubun** [comment]
I confirmed it's working. First, check the device name or path by looking at:

```bash
$ target/debug/xremap config.yml
Selecting devices from the following list:
------------------------------------------------------------------------------
/dev/input/event0 : Power Button
/dev/input/event1 : Power Button
/dev/input/event2 : PFU Limited  HHKB Professional JP
/dev/input/event3 : Logitech Wireless Mouse
/dev/input/event4 : Apple, Inc. USB-C to 3.5mm Headphone Jack Adapter
/dev/input/event5 : HDA NVidia HDMI/DP,pcm=3
/dev/input/event6 : HDA NVidia HDMI/DP,pcm=7
/dev/input/event7 : HDA NVidia HDMI/DP,pcm=8
/dev/input/event8 : HDA NVidia HDMI/DP,pcm=9
/dev/input/event9 : HDA NVidia HDMI/DP,pcm=10
/dev/input/event10: HDA NVidia HDMI/DP,pcm=11
/dev/input/event11: HDA NVidia HDMI/DP,pcm=12
/dev/input/event12: HD-Audio Generic Front Mic
/dev/input/event13: HD-Audio Generic Rear Mic
/dev/input/event14: HD-Audio Generic Line
/dev/input/event15: HD-Audio Generic Line Out Front
/dev/input/event16: HD-Audio Generic Line Out Surround
/dev/input/event17: HD-Audio Generic Line Out CLFE
/dev/input/event18: HD-Audio Generic Front Headphone
```

Second, specify device names or paths for both your mouse and your keyboard if you want to remap both. By default, xremap tries to target only keyboards, so you need to explicitly specify it.

```bash
$ xremap config.yml --device 'Logitech Wireless Mouse' --device 'PFU Limited  HHKB Professional JP'
```

Then, to check the key name, let's restart xremap with `RUST_LOG=debug` and try pushing buttons you want to remap:

```bash
[2021-12-25T21:17:25Z DEBUG xremap::event_handler] => 1: BTN_LEFT
[2021-12-25T21:17:25Z DEBUG xremap::event_handler] 1: BTN_LEFT
[2021-12-25T21:17:25Z DEBUG xremap::event_handler] => 0: BTN_LEFT
[2021-12-25T21:17:25Z DEBUG xremap::event_handler] 0: BTN_LEFT
[2021-12-25T21:17:26Z DEBUG xremap::event_handler] => 1: BTN_MIDDLE
[2021-12-25T21:17:26Z DEBUG xremap::event_handler] 1: BTN_MIDDLE
[2021-12-25T21:17:26Z DEBUG xremap::event_handler] => 0: BTN_MIDDLE
[2021-12-25T21:17:26Z DEBUG xremap::event_handler] 0: BTN_MIDDLE
[2021-12-25T21:17:26Z DEBUG xremap::event_handler] => 1: BTN_RIGHT
[2021-12-25T21:17:26Z DEBUG xremap::event_handler] 1: BTN_RIGHT
[2021-12-25T21:17:27Z DEBUG xremap::event_handler] => 0: BTN_RIGHT
[2021-12-25T21:17:27Z DEBUG xremap::event_handler] 0: BTN_RIGHT
```

My mouse had `BTN_LEFT`, `BTN_MIDDLE`, and `BTN_RIGHT`. I'm not sure what mouse-button 4 is actually named, but let's say it was BTN_4, an example config to remap mouse-button 4 to ctrl would be:

```
modmap:
  - name: Mouse-button 4 to Ctrl
    remap:
      BTN_4: KEY_LEFTCTRL
```

Note that we only support any `KEY_*` and the following `BTN_*`: https://github.com/k0kubun/xremap/blob/e300f6616fb56023fd498fa049ee3bd005e91cc8/src/output.rs#L6-L18

If your mouse button wasn't included in it, please let me know.

**Comment by N4tus** [comment]
While my mouse was found the the button i wanted to remap was show with RUST_LOG=debug, a remap from `BTN_EXTRA` (the actual name)  to `KEY_LEFTCTRL` only sort of worked. Pressing `BTN_EXTRA` triggered both a press and release of `KEY_LEFTCTRL`, which is unfortunate, since i would expect it to mimic my mouse button. 

Also other mouse buttons aside from left,right, and wheel stopped working normally (but still recorded in a log)
