### ISSUE TITLE
Autoselects YubiKey device

### ISSUE THREAD

**Issue by kbknapp** [k0kubun/xremap#46]
If I don't use the `--device` flag, it autoselects my keyboard (from a Thinkpad T14s) and my Yubikey. I haven't looked at the source, but I'm guessing it's just using a heuristic of searching for `*key*`.

**Comment by k0kubun** [comment]
Only devices with `Space`, `A`, and `Z` and without a mouse left button are considered a keyboard: https://github.com/k0kubun/xremap/blob/2557edb190aa10a091963b2cb459834a07d34f45/src/input.rs#L140-L144 As I don't have a YubiKey and am not aware of how Linux recognizes it, is there any suggestion on how we could skip selecting it?

**Comment by kbknapp** [comment]
That's a reasonable heuristic. So without diving into whether or not certain devices should be automatically ignored (I.e. expanding the heuristic), just providing a way to ignore devices based off the name is fine. I.e. something like`--ignore yubikey`.

**Comment by k0kubun** [comment]
Supported the option in v0.1.4. I hope it's helpful for you. Please let me know if it works as you intended.
