### ISSUE TITLE
[Suggestion] Add definitions for modifier keys

### ISSUE THREAD

**Issue by acomagu** [k0kubun/xremap#5]
I'm using rbindkeys and Hiragana-Katakana key for some useful key remaps.
But it cannot be in xkremap now.

We have a lot that possible to be modifier key, not only Ctrl, Alt, Shift and Super.
They all must be able to be used in it.

Thanks.

**Comment by k0kubun** [comment]
Could you show me your rbindkeys config to test the behavior?

**Comment by acomagu** [comment]
Thank you for quick reply.

I write like below:

    bind_key [KEY_KATAKANAHIRAGANA, KEY_H], KEY_PAGEDOWN
    bind_key [KEY_KATAKANAHIRAGANA, KEY_F], KEY_PAGEUP

The whole my config file is here: [https://github.com/acomagu/dotfiles/blob/master/.rbindkeys.rb](https://github.com/acomagu/dotfiles/blob/master/.rbindkeys.rb)

**Comment by k0kubun** [comment]
I guess it's already there https://github.com/k0kubun/xremap/blob/7a2ec961f38db670790460f91cddaec7dc1dce1e/src/x11_constants.c#L39
