### ISSUE TITLE
Mapping Mouse Keys works, but disabled original function fo unmaped mouse buttons.

### ISSUE THREAD

**Issue by N4tus** [k0kubun/xremap#57]
Testing the solution to my first issue (#44), the remap works, but other unmapped keys (except left, right, and wheel) do not function anymore. `BTN_SIDE` (the unmapped key) usually triggered a back action that e.g. goes to the last web-page. Now it does nothing.

**Comment by k0kubun** [comment]
As to `BTN_SIDE`, could you test this branch https://github.com/k0kubun/xremap/pull/58?

Also, to fully understand your situation and the problem you want to solve, may I ask you to paste the entire `RUST_LOG=debug` logs and another version that demonstrates the expected behavior?

**Comment by N4tus** [comment]
I can confirm that with branch #58 it works exactly as i imagined.

**Comment by k0kubun** [comment]
Oh, okay. Thank you for your confirmation. I'll just release it then.
