### ISSUE TITLE
Binding only when using english keyboard layout

### ISSUE THREAD

**Issue by abdallahz3** [k0kubun/xremap#66]
Hi,
I have something like this in my config
      KEY_SEMICOLON: SHIFT-KEY_SEMICOLON
      SHIFT-KEY_SEMICOLON: KEY_SEMICOLON

but I only want to have this mapping only while using `en` keyboard layout, Is that possible?

**Comment by k0kubun** [comment]
How do you change a keyboard layout? `setxkbmap`? Also, do you use different layouts for a single keyboard, or do you just use different layouts for different keyboards?

**Comment by k0kubun** [comment]
Closing until we have further information and this becomes actionable on my end.
