### ISSUE TITLE
Missing Hyper key

### ISSUE THREAD

**Issue by nat-418** [k0kubun/xremap#81]
I would like to map Hyper as a modifier but I am not sure how to modify xremap to do this. Here is a link to a Gist where I do so using xmodmap: https://gist.github.com/nat-418/135a62fb9f37cc87cd70af1ab72e276a

**Comment by k0kubun** [comment]
We call Hyper as Super in xremap. You may refer to the key as `Super_L` or `Super_R` under `modmap:`.

**Comment by k0kubun** [comment]
> Set CapsLock to Control and Escape to Hyper

Example:

```yml
modmap:
  - remap:
      CapsLock: Control_L
      Esc: Hyper_L
```

**Comment by nat-418** [comment]
I see, thanks for the clarification. I just learned that Hyper is apparently virtualized in X.

**Comment by nat-418** [comment]
> > Set CapsLock to Control and Escape to Hyper
> 
> Example:
> 
> ```yaml
> modmap:
>   - remap:
>       CapsLock: Control_L
>       Esc: Hyper_L
> ```

I tried this initially and got the following error:
```
Error: Failed to load config 'config.yml': modmap[0].remap: data did not match any variant of untagged enum KeyAction at line 4 column 15
```

**Comment by k0kubun** [comment]
lol, I ended up mentioning `Hyper_L` in my YAML. It should at least be:

```yml
modmap:
  - remap:
      CapsLock: Control_L
      Esc: Super_L
```

Please make sure you're using the latest xremap too.

```bash
$ xremap --version
xremap 0.3.0

$ cat /tmp/a.yml
modmap:
  - remap:
      CapsLock: Control_L
      Esc: Super_L

$ xremap /tmp/a.yml
Selecting devices from the following list:
------------------------------------------------------------------------------
...
```

**Comment by nat-418** [comment]
happens to the best of us. thanks for this great software. it does what i was using three different tools to do on X in an elegant, portable way.
