### ISSUE TITLE
Per-app mapping support for GNOME 42

### ISSUE THREAD

**Issue by dottorblaster** [k0kubun/xremap#88]
On my GNOME 42.0 system I have a strange behavior whenever I try to use per-app key remapping. The first time I try to use the per-app bound mappings, I have this error message:

```
GnomeClient#connect() failed: I/O error: No such file or directory (os error 2)
application-client: GNOME (supported: false)
```

I tried to poke a little with the source code, and I came to the conclusion that `zbus` might need an update, but it could cost a lot because the new 2.x version leverages a lot of async/await methods.

Any thoughts?

**Comment by k0kubun** [comment]
One of the users taught me how to address this, so I can take a look at it. Please allow me to have some time for working on this.

**Comment by dottorblaster** [comment]
Thank you for your amazing job, absolutely take all the time you need, no pressures!

**Comment by k0kubun** [comment]
Could you test https://github.com/k0kubun/xremap/pull/94? I submitted the extension for a review at https://extensions.gnome.org, but the review is still pending and you need to `git clone` the extension for now.

**Comment by k0kubun** [comment]
Actually, I already released it as v0.4.0. Please let me know if it doesn't work.

**Comment by dottorblaster** [comment]
It's working like a charm, thank you so much!

**Comment by petrstepanov** [comment]
Hi, thank you for developing this software. I am running into the same issue on Fedora 36 with GNOME Shell 42.1:

```
GnomeClient#connect() failed: I/O error: No such file or directory (os error 2)
GnomeClient#connect() failed: I/O error: No such file or directory (os error 2)
application-client: GNOME (supported: false)
```

I tried installing `xremap` by 1) downloading latest binary from the Releases page 2) Installing from the cargo repository 3) cloning and building latest branch with `cargo`. The gnome extension I tried to install from from both - official extensions website as well as your git repository.

I run `xremap` with sudo and modified the `/usr/share/dbus-1/session.conf` file according to the readme.

P.S.: If I'm running `xremap` without sudo I get: `Error: Failed to prepare an output device: Permission denied (os error 13)`

Let me know if I can help test the functionality somehow. Thanks again.

**Comment by k0kubun** [comment]
As to "I/O error: No such file or directory (os error 2)", it tries to open a D-Bus session using `$DBUS_SESSION_BUS_ADDRESS`. In my environment, it does exist:

```
$ echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/run/user/1000/bus
$ file /run/user/1000/bus
/run/user/1000/bus: socket
```

If you have a `$DBUS_SESSION_BUS_ADDRESS` that actually exists, it should work.

---

>  If I'm running xremap without sudo I get: Error: Failed to prepare an output device: Permission denied (os error 13)

Have you followed the "If you want to run xremap without sudo, click here." instructions in the README?

**Comment by petrstepanov** [comment]
Thank you for your speedy reply. I believe I made a mistake somewhere. Managed to get things working now.
