### ISSUE TITLE
Vim-like modal editing

### ISSUE THREAD

**Issue by leoc** [k0kubun/xremap#89]
First let me say, thanks for this project. I love it!

Recently I switched to evil-mode in emacs and I wondered if it would be (sort of) easy to add modal editing to xremap? Like a per-app modal state that switches keymaps according to mode. E.g. insert and visual mode.

That would be awesome in gtk apps, browser apps, and others that do not support modal editing.

I see that key combos are supported, this should allow something like `viw`-alike thingies.

**Comment by k0kubun** [comment]
Could you test this branch and check if it's what you want? https://github.com/k0kubun/xremap/pull/93

**Comment by k0kubun** [comment]
While I haven't got a response from you and thus I'm not sure if it's exactly what you want, I'm open to maintaining the idea in general, so I'll just merge what I already have as is. Thank you.

**Comment by leoc** [comment]
Oh my! You were soo fast! I haven't had the time to look at your branch yet and totally forgot! I am so sorry for not replying.

Thank you for your awesome project. I see how quickly you reply to issues and how fast you try to provide fixes and enhancements. So let me say this: Thank you, thank you, thank you! I am sure this does not go unnoticed. I enjoy seeing your prolific output for sure! 

<img src="https://media4.giphy.com/media/WV9Xx9itqEIu8GQloO/giphy.gif"/>
