### ISSUE TITLE
Suggestion for README

### ISSUE THREAD

**Issue by andreasaronsson** [k0kubun/xremap#99]
Hi, 

Congratulations on a very useful project.

On Arch linux I had to load module uinput to make it possible to use without sudo.
Took me a good while to figure out so hopefully it can help someone else. 

`/etc/modules-load.d/uinput.conf`

```
uinput
```

`/etc/udev/rules.d/99-input.rules`

```
KERNEL=="uinput", GROUP="input", MODE="0660"
```

It would also be helpful to have your (as I understand it) prefered way to start

`~/.config/systemd/user/xremap.service`

```
[Unit]
Description=xremap

[Service]
Type=simple
Restart=always
ExecStart=xremap ~/.config/xremap/config.yml --watch

[Install]
WantedBy=default.target
```

**Comment by k0kubun** [comment]
Thanks. Suggestion for this issue: Could you suggest this change as a pull request?

**Comment by andreasaronsson** [comment]
https://github.com/k0kubun/xremap/pull/103 HTH

**Comment by k0kubun** [comment]
merged, thanks :+1:
